CREATE TABLE IF NOT EXISTS diagnostic_management_reports (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,run_id TEXT NOT NULL,report_number INTEGER NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL CHECK(status='Emitido'),payload_json TEXT NOT NULL,input_hash TEXT NOT NULL,issued_by TEXT NOT NULL,issued_at TEXT NOT NULL,
 FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(run_id) REFERENCES diagnostic_runs(id),UNIQUE(tenant_id,report_number),UNIQUE(tenant_id,run_id)
);
CREATE TABLE IF NOT EXISTS diagnostic_improvement_actions (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,run_id TEXT NOT NULL,result_id TEXT NOT NULL,organization_id TEXT NOT NULL,title TEXT NOT NULL,recommendation_snapshot TEXT NOT NULL,owner_email TEXT NOT NULL,due_date TEXT NOT NULL,priority TEXT NOT NULL CHECK(priority IN ('Baixa','Média','Alta','Crítica')),status TEXT NOT NULL CHECK(status IN ('Aberta','Em curso','Concluída','Cancelada')),completion_evidence TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,completed_at TEXT,
 FOREIGN KEY(run_id) REFERENCES diagnostic_runs(id),FOREIGN KEY(result_id) REFERENCES diagnostic_results(id),FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE INDEX IF NOT EXISTS diagnostic_actions_owner_status_idx ON diagnostic_improvement_actions(tenant_id,owner_email,status,due_date);
CREATE TRIGGER IF NOT EXISTS diagnostic_report_approved_run BEFORE INSERT ON diagnostic_management_reports WHEN NOT EXISTS (SELECT 1 FROM diagnostic_runs r WHERE r.id=NEW.run_id AND r.tenant_id=NEW.tenant_id AND r.status='Aprovado') BEGIN SELECT RAISE(ABORT,'diagnostic report requires approved run'); END;
CREATE TRIGGER IF NOT EXISTS diagnostic_report_immutable_update BEFORE UPDATE ON diagnostic_management_reports BEGIN SELECT RAISE(ABORT,'diagnostic management reports are immutable'); END;
CREATE TRIGGER IF NOT EXISTS diagnostic_report_immutable_delete BEFORE DELETE ON diagnostic_management_reports BEGIN SELECT RAISE(ABORT,'diagnostic management reports cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS diagnostic_action_approved_result BEFORE INSERT ON diagnostic_improvement_actions WHEN NOT EXISTS (SELECT 1 FROM diagnostic_results d JOIN diagnostic_runs r ON r.id=d.run_id AND r.tenant_id=d.tenant_id WHERE d.id=NEW.result_id AND d.tenant_id=NEW.tenant_id AND d.run_id=NEW.run_id AND r.organization_id=NEW.organization_id AND r.status='Aprovado') BEGIN SELECT RAISE(ABORT,'diagnostic action requires approved result'); END;
CREATE TRIGGER IF NOT EXISTS diagnostic_action_transition BEFORE UPDATE ON diagnostic_improvement_actions WHEN NEW.tenant_id<>OLD.tenant_id OR NEW.run_id<>OLD.run_id OR NEW.result_id<>OLD.result_id OR NEW.organization_id<>OLD.organization_id OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at OR NOT ((OLD.status='Aberta' AND NEW.status IN ('Em curso','Cancelada')) OR (OLD.status='Em curso' AND NEW.status IN ('Concluída','Cancelada'))) OR (NEW.status='Concluída' AND (NEW.completion_evidence IS NULL OR length(trim(NEW.completion_evidence))<10 OR NEW.completed_at IS NULL)) BEGIN SELECT RAISE(ABORT,'invalid diagnostic action transition'); END;
CREATE TRIGGER IF NOT EXISTS diagnostic_action_no_delete BEFORE DELETE ON diagnostic_improvement_actions BEGIN SELECT RAISE(ABORT,'diagnostic actions cannot be deleted'); END;
