CREATE TABLE IF NOT EXISTS workforce_plans (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,name TEXT NOT NULL,currency TEXT NOT NULL,start_period TEXT NOT NULL,end_period TEXT NOT NULL,version_number INTEGER NOT NULL CHECK(version_number>0),status TEXT NOT NULL CHECK(status IN ('Rascunho','Submetido','Aprovado')),created_by TEXT NOT NULL,created_at TEXT NOT NULL,submitted_by TEXT,submitted_at TEXT,approved_by TEXT,approved_at TEXT,approval_hash TEXT,
 FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(organization_id) REFERENCES organizations(id),UNIQUE(tenant_id,organization_id,name,version_number)
);
CREATE TABLE IF NOT EXISTS workforce_plan_lines (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,plan_id TEXT NOT NULL,job_title TEXT NOT NULL,department_code TEXT,period TEXT NOT NULL,headcount INTEGER NOT NULL CHECK(headcount>=0),monthly_cost_minor INTEGER NOT NULL CHECK(monthly_cost_minor>=0),movement_type TEXT NOT NULL CHECK(movement_type IN ('Base','Nova contratação','Substituição','Redução')),assumption_note TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,
 FOREIGN KEY(plan_id) REFERENCES workforce_plans(id),UNIQUE(tenant_id,plan_id,job_title,department_code,period,movement_type)
);
CREATE INDEX IF NOT EXISTS workforce_plan_scope_idx ON workforce_plans(tenant_id,organization_id,status,start_period);
CREATE TRIGGER IF NOT EXISTS workforce_plan_line_guard BEFORE INSERT ON workforce_plan_lines WHEN NEW.period NOT GLOB '[0-9][0-9][0-9][0-9]-[0-1][0-9]' OR length(trim(NEW.assumption_note))<5 OR NOT EXISTS(SELECT 1 FROM workforce_plans p WHERE p.id=NEW.plan_id AND p.tenant_id=NEW.tenant_id AND p.status='Rascunho' AND NEW.period BETWEEN p.start_period AND p.end_period) BEGIN SELECT RAISE(ABORT,'invalid workforce plan line'); END;
CREATE TRIGGER IF NOT EXISTS workforce_plan_line_immutable_update BEFORE UPDATE ON workforce_plan_lines BEGIN SELECT RAISE(ABORT,'workforce plan lines are immutable'); END;
CREATE TRIGGER IF NOT EXISTS workforce_plan_line_no_delete BEFORE DELETE ON workforce_plan_lines BEGIN SELECT RAISE(ABORT,'workforce plan lines cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS workforce_plan_transition BEFORE UPDATE ON workforce_plans WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.organization_id<>OLD.organization_id OR NEW.name<>OLD.name OR NEW.currency<>OLD.currency OR NEW.start_period<>OLD.start_period OR NEW.end_period<>OLD.end_period OR NEW.version_number<>OLD.version_number OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at OR NOT ((OLD.status='Rascunho' AND NEW.status='Submetido' AND EXISTS(SELECT 1 FROM workforce_plan_lines l WHERE l.plan_id=OLD.id AND l.tenant_id=OLD.tenant_id)) OR (OLD.status='Submetido' AND NEW.status='Aprovado' AND NEW.approval_hash IS NOT NULL)) BEGIN SELECT RAISE(ABORT,'invalid workforce plan transition'); END;
CREATE TRIGGER IF NOT EXISTS workforce_plan_no_delete BEFORE DELETE ON workforce_plans BEGIN SELECT RAISE(ABORT,'workforce plans cannot be deleted'); END;
