CREATE TABLE IF NOT EXISTS recruitment_requisitions (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,title TEXT NOT NULL,department_code TEXT,positions INTEGER NOT NULL CHECK(positions>0),target_start_date TEXT NOT NULL,employment_type TEXT NOT NULL,budget_monthly_minor INTEGER NOT NULL CHECK(budget_monthly_minor>=0),currency TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Rascunho','Aberta','Fechada','Cancelada')),business_reason TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,approved_by TEXT,approved_at TEXT,FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS recruitment_candidates (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,full_name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT,source TEXT NOT NULL,consent_at TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,email)
);
CREATE TABLE IF NOT EXISTS recruitment_applications (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,requisition_id TEXT NOT NULL,candidate_id TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Recebida','Triagem','Entrevista','Oferta','Contratada','Rejeitada')),rating INTEGER CHECK(rating BETWEEN 1 AND 5),decision_note TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(requisition_id) REFERENCES recruitment_requisitions(id),FOREIGN KEY(candidate_id) REFERENCES recruitment_candidates(id),UNIQUE(tenant_id,requisition_id,candidate_id)
);
CREATE TABLE IF NOT EXISTS employee_onboarding_cases (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,application_id TEXT NOT NULL,employee_id TEXT,status TEXT NOT NULL CHECK(status IN ('Preparação','Em curso','Concluído','Cancelado')),start_date TEXT NOT NULL,owner_email TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,completed_at TEXT,FOREIGN KEY(application_id) REFERENCES recruitment_applications(id),FOREIGN KEY(employee_id) REFERENCES employees(id),UNIQUE(tenant_id,application_id)
);
CREATE TABLE IF NOT EXISTS employee_onboarding_tasks (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,case_id TEXT NOT NULL,title TEXT NOT NULL,owner_email TEXT NOT NULL,due_date TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Pendente','Concluída')),evidence TEXT,created_at TEXT NOT NULL,completed_at TEXT,FOREIGN KEY(case_id) REFERENCES employee_onboarding_cases(id)
);
CREATE INDEX IF NOT EXISTS recruitment_scope_idx ON recruitment_requisitions(tenant_id,organization_id,status,target_start_date);
CREATE TRIGGER IF NOT EXISTS recruitment_requisition_transition BEFORE UPDATE ON recruitment_requisitions WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.organization_id<>OLD.organization_id OR NEW.title<>OLD.title OR NEW.positions<>OLD.positions OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at OR NOT ((OLD.status='Rascunho' AND NEW.status='Aberta' AND NEW.approved_by IS NOT NULL) OR (OLD.status='Aberta' AND NEW.status IN ('Fechada','Cancelada'))) BEGIN SELECT RAISE(ABORT,'invalid recruitment requisition transition'); END;
CREATE TRIGGER IF NOT EXISTS recruitment_application_transition BEFORE UPDATE ON recruitment_applications WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.requisition_id<>OLD.requisition_id OR NEW.candidate_id<>OLD.candidate_id OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at OR NOT ((OLD.status='Recebida' AND NEW.status IN ('Triagem','Rejeitada')) OR (OLD.status='Triagem' AND NEW.status IN ('Entrevista','Rejeitada')) OR (OLD.status='Entrevista' AND NEW.status IN ('Oferta','Rejeitada')) OR (OLD.status='Oferta' AND NEW.status IN ('Contratada','Rejeitada'))) BEGIN SELECT RAISE(ABORT,'invalid recruitment application transition'); END;
CREATE TRIGGER IF NOT EXISTS onboarding_task_completion BEFORE UPDATE ON employee_onboarding_tasks WHEN NEW.status='Concluída' AND (OLD.status<>'Pendente' OR NEW.evidence IS NULL OR length(trim(NEW.evidence))<5 OR NEW.completed_at IS NULL) BEGIN SELECT RAISE(ABORT,'onboarding task requires evidence'); END;
CREATE TRIGGER IF NOT EXISTS onboarding_case_transition BEFORE UPDATE ON employee_onboarding_cases WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.application_id<>OLD.application_id OR NEW.owner_email<>OLD.owner_email OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at OR NOT ((OLD.status='Preparação' AND NEW.status='Em curso') OR (OLD.status='Em curso' AND NEW.status='Concluído' AND NEW.completed_at IS NOT NULL AND EXISTS(SELECT 1 FROM employee_onboarding_tasks t WHERE t.case_id=OLD.id) AND NOT EXISTS(SELECT 1 FROM employee_onboarding_tasks t WHERE t.case_id=OLD.id AND t.status<>'Concluída'))) BEGIN SELECT RAISE(ABORT,'invalid onboarding case transition'); END;
CREATE TRIGGER IF NOT EXISTS recruitment_records_no_delete BEFORE DELETE ON recruitment_applications BEGIN SELECT RAISE(ABORT,'recruitment applications cannot be deleted'); END;
