CREATE TABLE IF NOT EXISTS attendance_shifts (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,start_minute INTEGER NOT NULL CHECK(start_minute BETWEEN 0 AND 1439),end_minute INTEGER NOT NULL CHECK(end_minute BETWEEN 0 AND 1439),break_minutes INTEGER NOT NULL DEFAULT 0 CHECK(break_minutes>=0),scheduled_minutes INTEGER NOT NULL CHECK(scheduled_minutes>0),status TEXT NOT NULL CHECK(status IN ('Ativo','Inativo')),created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,code),FOREIGN KEY(tenant_id) REFERENCES tenants(id)
);
CREATE TABLE IF NOT EXISTS attendance_assignments (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,employee_id TEXT NOT NULL,shift_id TEXT NOT NULL,effective_from TEXT NOT NULL,effective_to TEXT,status TEXT NOT NULL CHECK(status IN ('Ativa','Encerrada')),created_by TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(employee_id) REFERENCES employees(id),FOREIGN KEY(shift_id) REFERENCES attendance_shifts(id)
);
CREATE TABLE IF NOT EXISTS attendance_entries (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,employee_id TEXT NOT NULL,work_date TEXT NOT NULL,clock_in TEXT NOT NULL,clock_out TEXT,source TEXT NOT NULL,worked_minutes INTEGER,scheduled_minutes INTEGER NOT NULL,overtime_minutes INTEGER,exception_code TEXT,note TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,employee_id,work_date),FOREIGN KEY(employee_id) REFERENCES employees(id)
);
CREATE TABLE IF NOT EXISTS attendance_timesheets (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,employee_id TEXT NOT NULL,period TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Rascunho','Submetido','Aprovado','Rejeitado')),worked_minutes INTEGER NOT NULL CHECK(worked_minutes>=0),scheduled_minutes INTEGER NOT NULL CHECK(scheduled_minutes>=0),overtime_minutes INTEGER NOT NULL CHECK(overtime_minutes>=0),entry_count INTEGER NOT NULL CHECK(entry_count>0),source_hash TEXT,submitted_by TEXT,submitted_at TEXT,decided_by TEXT,decided_at TEXT,decision_note TEXT,created_at TEXT NOT NULL,UNIQUE(tenant_id,employee_id,period),FOREIGN KEY(employee_id) REFERENCES employees(id)
);
CREATE INDEX IF NOT EXISTS attendance_entry_scope_idx ON attendance_entries(tenant_id,employee_id,work_date);
CREATE INDEX IF NOT EXISTS attendance_timesheet_scope_idx ON attendance_timesheets(tenant_id,period,status);
CREATE TRIGGER IF NOT EXISTS attendance_assignment_scope BEFORE INSERT ON attendance_assignments WHEN NOT EXISTS(SELECT 1 FROM employees e JOIN attendance_shifts s ON s.id=NEW.shift_id AND s.tenant_id=NEW.tenant_id WHERE e.id=NEW.employee_id AND e.tenant_id=NEW.tenant_id) BEGIN SELECT RAISE(ABORT,'attendance assignment outside tenant'); END;
CREATE TRIGGER IF NOT EXISTS attendance_entry_scope BEFORE INSERT ON attendance_entries WHEN NOT EXISTS(SELECT 1 FROM employees e WHERE e.id=NEW.employee_id AND e.tenant_id=NEW.tenant_id) BEGIN SELECT RAISE(ABORT,'attendance entry outside tenant'); END;
CREATE TRIGGER IF NOT EXISTS attendance_entry_close BEFORE UPDATE ON attendance_entries WHEN OLD.clock_out IS NOT NULL OR NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.employee_id<>OLD.employee_id OR NEW.work_date<>OLD.work_date OR NEW.clock_in<>OLD.clock_in OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at OR NEW.clock_out IS NULL OR NEW.worked_minutes IS NULL OR NEW.overtime_minutes IS NULL BEGIN SELECT RAISE(ABORT,'invalid attendance entry close'); END;
CREATE TRIGGER IF NOT EXISTS attendance_entry_no_delete BEFORE DELETE ON attendance_entries BEGIN SELECT RAISE(ABORT,'attendance entries cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS attendance_timesheet_transition BEFORE UPDATE ON attendance_timesheets WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.employee_id<>OLD.employee_id OR NEW.period<>OLD.period OR NEW.worked_minutes<>OLD.worked_minutes OR NEW.scheduled_minutes<>OLD.scheduled_minutes OR NEW.overtime_minutes<>OLD.overtime_minutes OR NEW.entry_count<>OLD.entry_count OR NEW.source_hash<>OLD.source_hash OR NEW.created_at<>OLD.created_at OR NOT ((OLD.status='Rascunho' AND NEW.status='Submetido' AND NEW.submitted_by IS NOT NULL AND NEW.submitted_at IS NOT NULL) OR (OLD.status='Submetido' AND NEW.status IN ('Aprovado','Rejeitado') AND NEW.decided_by IS NOT NULL AND NEW.decided_at IS NOT NULL)) BEGIN SELECT RAISE(ABORT,'invalid attendance timesheet transition'); END;
CREATE TRIGGER IF NOT EXISTS attendance_timesheet_no_delete BEFORE DELETE ON attendance_timesheets BEGIN SELECT RAISE(ABORT,'attendance timesheets cannot be deleted'); END;
