CREATE TABLE IF NOT EXISTS payroll_loans (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,employee_id TEXT NOT NULL,loan_type TEXT NOT NULL CHECK(loan_type IN ('Empréstimo','Adiantamento')),reference TEXT NOT NULL,currency TEXT NOT NULL,principal_minor INTEGER NOT NULL CHECK(principal_minor>0),installment_count INTEGER NOT NULL CHECK(installment_count>0),first_period TEXT NOT NULL,purpose TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Pendente','Aprovado','Rejeitado','Liquidado','Cancelado')),outstanding_minor INTEGER NOT NULL CHECK(outstanding_minor>=0),requested_by TEXT NOT NULL,requested_at TEXT NOT NULL,decided_by TEXT,decided_at TEXT,decision_note TEXT,completed_at TEXT,UNIQUE(tenant_id,reference),FOREIGN KEY(employee_id) REFERENCES employees(id)
);
CREATE TABLE IF NOT EXISTS payroll_loan_installments (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,loan_id TEXT NOT NULL,sequence_number INTEGER NOT NULL CHECK(sequence_number>0),period TEXT NOT NULL,amount_minor INTEGER NOT NULL CHECK(amount_minor>0),status TEXT NOT NULL CHECK(status IN ('Programada','Liquidada')),paid_at TEXT,UNIQUE(tenant_id,loan_id,sequence_number),UNIQUE(tenant_id,loan_id,period),FOREIGN KEY(loan_id) REFERENCES payroll_loans(id)
);
CREATE TABLE IF NOT EXISTS payroll_loan_deductions (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,loan_id TEXT NOT NULL,installment_id TEXT NOT NULL,run_id TEXT NOT NULL,run_line_id TEXT NOT NULL,amount_minor INTEGER NOT NULL CHECK(amount_minor>0),status TEXT NOT NULL CHECK(status IN ('Calculada','Liquidada')),created_at TEXT NOT NULL,settled_at TEXT,UNIQUE(tenant_id,installment_id),FOREIGN KEY(loan_id) REFERENCES payroll_loans(id),FOREIGN KEY(installment_id) REFERENCES payroll_loan_installments(id),FOREIGN KEY(run_id) REFERENCES payroll_runs(id),FOREIGN KEY(run_line_id) REFERENCES payroll_run_lines(id)
);
CREATE INDEX IF NOT EXISTS payroll_loans_scope_idx ON payroll_loans(tenant_id,employee_id,status);
CREATE TRIGGER IF NOT EXISTS payroll_loan_scope BEFORE INSERT ON payroll_loans WHEN NOT EXISTS(SELECT 1 FROM employees e WHERE e.id=NEW.employee_id AND e.tenant_id=NEW.tenant_id) BEGIN SELECT RAISE(ABORT,'payroll loan outside tenant'); END;
CREATE TRIGGER IF NOT EXISTS payroll_loan_transition BEFORE UPDATE ON payroll_loans WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.employee_id<>OLD.employee_id OR NEW.loan_type<>OLD.loan_type OR NEW.reference<>OLD.reference OR NEW.currency<>OLD.currency OR NEW.principal_minor<>OLD.principal_minor OR NEW.installment_count<>OLD.installment_count OR NEW.first_period<>OLD.first_period OR NEW.purpose<>OLD.purpose OR NEW.requested_by<>OLD.requested_by OR NEW.requested_at<>OLD.requested_at OR NOT ((OLD.status='Pendente' AND NEW.status IN ('Aprovado','Rejeitado','Cancelado')) OR (OLD.status='Aprovado' AND NEW.status='Liquidado' AND NEW.outstanding_minor=0 AND NEW.completed_at IS NOT NULL) OR (OLD.status=NEW.status AND NEW.outstanding_minor<=OLD.outstanding_minor)) BEGIN SELECT RAISE(ABORT,'invalid payroll loan transition'); END;
CREATE TRIGGER IF NOT EXISTS payroll_loan_no_delete BEFORE DELETE ON payroll_loans BEGIN SELECT RAISE(ABORT,'payroll loans cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS payroll_installment_transition BEFORE UPDATE ON payroll_loan_installments WHEN OLD.status<>'Programada' OR NEW.status<>'Liquidada' OR NEW.paid_at IS NULL OR NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.loan_id<>OLD.loan_id OR NEW.sequence_number<>OLD.sequence_number OR NEW.period<>OLD.period OR NEW.amount_minor<>OLD.amount_minor BEGIN SELECT RAISE(ABORT,'invalid payroll installment transition'); END;
CREATE TRIGGER IF NOT EXISTS payroll_installment_no_delete BEFORE DELETE ON payroll_loan_installments BEGIN SELECT RAISE(ABORT,'payroll installments cannot be deleted'); END;
