CREATE TABLE IF NOT EXISTS payroll_adjustments (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,employee_id TEXT NOT NULL,reference TEXT NOT NULL,adjustment_type TEXT NOT NULL CHECK(adjustment_type IN ('Retroativo','Correção')),category TEXT NOT NULL CHECK(category IN ('Earning','Deduction')),source_period TEXT NOT NULL,payment_period TEXT NOT NULL,currency TEXT NOT NULL,amount_minor INTEGER NOT NULL CHECK(amount_minor>0),reason TEXT NOT NULL,evidence TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Pendente','Aprovado','Rejeitado','Processado','Cancelado')),requested_by TEXT NOT NULL,requested_at TEXT NOT NULL,decided_by TEXT,decided_at TEXT,decision_note TEXT,processed_at TEXT,UNIQUE(tenant_id,reference),FOREIGN KEY(employee_id) REFERENCES employees(id)
);
CREATE TABLE IF NOT EXISTS payroll_adjustment_applications (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,adjustment_id TEXT NOT NULL,run_id TEXT NOT NULL,run_line_id TEXT NOT NULL,amount_minor INTEGER NOT NULL CHECK(amount_minor>0),category TEXT NOT NULL CHECK(category IN ('Earning','Deduction')),status TEXT NOT NULL CHECK(status IN ('Calculado','Processado')),created_at TEXT NOT NULL,processed_at TEXT,UNIQUE(tenant_id,adjustment_id),FOREIGN KEY(adjustment_id) REFERENCES payroll_adjustments(id),FOREIGN KEY(run_id) REFERENCES payroll_runs(id),FOREIGN KEY(run_line_id) REFERENCES payroll_run_lines(id)
);
CREATE INDEX IF NOT EXISTS payroll_adjustments_scope_idx ON payroll_adjustments(tenant_id,employee_id,payment_period,status);
CREATE TRIGGER IF NOT EXISTS payroll_adjustment_scope BEFORE INSERT ON payroll_adjustments WHEN NOT EXISTS(SELECT 1 FROM employees e WHERE e.id=NEW.employee_id AND e.tenant_id=NEW.tenant_id) BEGIN SELECT RAISE(ABORT,'payroll adjustment outside tenant'); END;
CREATE TRIGGER IF NOT EXISTS payroll_adjustment_period BEFORE INSERT ON payroll_adjustments WHEN NEW.source_period>NEW.payment_period BEGIN SELECT RAISE(ABORT,'payroll adjustment source period is after payment period'); END;
CREATE TRIGGER IF NOT EXISTS payroll_adjustment_transition BEFORE UPDATE ON payroll_adjustments WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.employee_id<>OLD.employee_id OR NEW.reference<>OLD.reference OR NEW.adjustment_type<>OLD.adjustment_type OR NEW.category<>OLD.category OR NEW.source_period<>OLD.source_period OR NEW.payment_period<>OLD.payment_period OR NEW.currency<>OLD.currency OR NEW.amount_minor<>OLD.amount_minor OR NEW.reason<>OLD.reason OR NEW.evidence<>OLD.evidence OR NEW.requested_by<>OLD.requested_by OR NEW.requested_at<>OLD.requested_at OR NOT ((OLD.status='Pendente' AND NEW.status IN ('Aprovado','Rejeitado','Cancelado')) OR (OLD.status='Aprovado' AND NEW.status='Processado' AND NEW.processed_at IS NOT NULL)) BEGIN SELECT RAISE(ABORT,'invalid payroll adjustment transition'); END;
CREATE TRIGGER IF NOT EXISTS payroll_adjustment_no_delete BEFORE DELETE ON payroll_adjustments BEGIN SELECT RAISE(ABORT,'payroll adjustments cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS payroll_adjustment_application_no_delete BEFORE DELETE ON payroll_adjustment_applications BEGIN SELECT RAISE(ABORT,'payroll adjustment applications cannot be deleted'); END;
