CREATE TABLE IF NOT EXISTS integration_sources (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,connector_type TEXT NOT NULL CHECK(connector_type IN ('API','SFTP','Ficheiro','Base de dados')),direction TEXT NOT NULL CHECK(direction IN ('Entrada','Saída','Bidirecional')),status TEXT NOT NULL CHECK(status IN ('Rascunho','Ativa','Suspensa')),created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,code)
);
CREATE TABLE IF NOT EXISTS integration_runs (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,source_id TEXT NOT NULL,organization_id TEXT,run_number INTEGER NOT NULL CHECK(run_number>0),idempotency_key TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Recebida','Validada','Aprovada','Rejeitada')),record_count INTEGER NOT NULL CHECK(record_count>=0),accepted_count INTEGER NOT NULL DEFAULT 0 CHECK(accepted_count>=0),rejected_count INTEGER NOT NULL DEFAULT 0 CHECK(rejected_count>=0),input_hash TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,validated_by TEXT,validated_at TEXT,decided_by TEXT,decided_at TEXT,decision_note TEXT,UNIQUE(tenant_id,source_id,run_number),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(source_id) REFERENCES integration_sources(id),FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE INDEX IF NOT EXISTS integration_sources_scope_idx ON integration_sources(tenant_id,status,code);
CREATE INDEX IF NOT EXISTS integration_runs_scope_idx ON integration_runs(tenant_id,source_id,status,created_at);
CREATE TRIGGER IF NOT EXISTS integration_run_scope BEFORE INSERT ON integration_runs WHEN NOT EXISTS(SELECT 1 FROM integration_sources s WHERE s.id=NEW.source_id AND s.tenant_id=NEW.tenant_id) OR (NEW.organization_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM organizations o WHERE o.id=NEW.organization_id AND o.tenant_id=NEW.tenant_id)) BEGIN SELECT RAISE(ABORT,'integration run outside tenant'); END;
CREATE TRIGGER IF NOT EXISTS integration_run_counts BEFORE UPDATE ON integration_runs WHEN NEW.accepted_count+NEW.rejected_count<>NEW.record_count AND NEW.status IN ('Validada','Aprovada') BEGIN SELECT RAISE(ABORT,'integration counts do not reconcile'); END;
CREATE TRIGGER IF NOT EXISTS integration_run_transition BEFORE UPDATE ON integration_runs WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.source_id<>OLD.source_id OR NOT ((OLD.status='Recebida' AND NEW.status='Validada') OR (OLD.status='Validada' AND NEW.status IN ('Aprovada','Rejeitada'))) BEGIN SELECT RAISE(ABORT,'invalid integration run transition'); END;
CREATE TRIGGER IF NOT EXISTS integration_source_no_delete BEFORE DELETE ON integration_sources BEGIN SELECT RAISE(ABORT,'integration sources cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS integration_run_no_delete BEFORE DELETE ON integration_runs BEGIN SELECT RAISE(ABORT,'integration runs cannot be deleted'); END;
