CREATE TABLE IF NOT EXISTS employee_document_types (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,requires_expiry INTEGER NOT NULL CHECK(requires_expiry IN (0,1)),confidentiality TEXT NOT NULL CHECK(confidentiality IN ('Normal','Confidencial','Restrito')),status TEXT NOT NULL CHECK(status IN ('Ativo','Inativo')),created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,code)
);
CREATE TABLE IF NOT EXISTS employee_documents (
 id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,employee_id TEXT NOT NULL,document_type_id TEXT NOT NULL,reference TEXT NOT NULL,issue_date TEXT NOT NULL,expiry_date TEXT,file_name TEXT NOT NULL,mime_type TEXT NOT NULL,file_size INTEGER NOT NULL CHECK(file_size>=0),storage_key TEXT NOT NULL,evidence_hash TEXT NOT NULL,version_number INTEGER NOT NULL CHECK(version_number>0),status TEXT NOT NULL CHECK(status IN ('Pendente','Aprovado','Rejeitado','Substituído')),submitted_by TEXT NOT NULL,submitted_at TEXT NOT NULL,decided_by TEXT,decided_at TEXT,decision_note TEXT,replaces_document_id TEXT,UNIQUE(tenant_id,employee_id,document_type_id,version_number),UNIQUE(tenant_id,storage_key),FOREIGN KEY(employee_id) REFERENCES employees(id),FOREIGN KEY(document_type_id) REFERENCES employee_document_types(id),FOREIGN KEY(replaces_document_id) REFERENCES employee_documents(id)
);
CREATE INDEX IF NOT EXISTS employee_document_types_scope_idx ON employee_document_types(tenant_id,status,category);
CREATE INDEX IF NOT EXISTS employee_documents_scope_idx ON employee_documents(tenant_id,employee_id,status,expiry_date);
CREATE TRIGGER IF NOT EXISTS employee_document_scope BEFORE INSERT ON employee_documents WHEN NOT EXISTS(SELECT 1 FROM employees e WHERE e.id=NEW.employee_id AND e.tenant_id=NEW.tenant_id) OR NOT EXISTS(SELECT 1 FROM employee_document_types t WHERE t.id=NEW.document_type_id AND t.tenant_id=NEW.tenant_id AND t.status='Ativo') BEGIN SELECT RAISE(ABORT,'employee document outside tenant'); END;
CREATE TRIGGER IF NOT EXISTS employee_document_expiry BEFORE INSERT ON employee_documents WHEN (SELECT requires_expiry FROM employee_document_types WHERE id=NEW.document_type_id)=1 AND NEW.expiry_date IS NULL BEGIN SELECT RAISE(ABORT,'employee document expiry required'); END;
CREATE TRIGGER IF NOT EXISTS employee_document_dates BEFORE INSERT ON employee_documents WHEN NEW.expiry_date IS NOT NULL AND NEW.expiry_date<NEW.issue_date BEGIN SELECT RAISE(ABORT,'employee document expiry before issue'); END;
CREATE TRIGGER IF NOT EXISTS employee_document_transition BEFORE UPDATE ON employee_documents WHEN NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.employee_id<>OLD.employee_id OR NEW.document_type_id<>OLD.document_type_id OR NEW.reference<>OLD.reference OR NEW.issue_date<>OLD.issue_date OR COALESCE(NEW.expiry_date,'')<>COALESCE(OLD.expiry_date,'') OR NEW.file_name<>OLD.file_name OR NEW.mime_type<>OLD.mime_type OR NEW.file_size<>OLD.file_size OR NEW.storage_key<>OLD.storage_key OR NEW.evidence_hash<>OLD.evidence_hash OR NEW.version_number<>OLD.version_number OR NEW.submitted_by<>OLD.submitted_by OR NEW.submitted_at<>OLD.submitted_at OR NOT ((OLD.status='Pendente' AND NEW.status IN ('Aprovado','Rejeitado')) OR (OLD.status='Aprovado' AND NEW.status='Substituído')) BEGIN SELECT RAISE(ABORT,'invalid employee document transition'); END;
CREATE TRIGGER IF NOT EXISTS employee_document_no_delete BEFORE DELETE ON employee_documents BEGIN SELECT RAISE(ABORT,'employee documents cannot be deleted'); END;
