import test from "node:test";
import assert from "node:assert/strict";
import {openApiDocument as spec} from "../lib/openapi.ts";
test("publishes OpenAPI 3.1 with stable v1 server",()=>{assert.equal(spec.openapi,"3.1.0");assert.equal(spec.servers[0].url,"/api/v1")});
test("documents every vertical slice API",()=>{for(const path of ["/session","/setup","/hcm","/performance","/payroll","/workforce","/dashboard","/management-reports","/readiness","/integrity"])assert.ok(spec.paths[path],path)});
test("documents tenant memberships and paid provisioning",()=>{assert.ok(spec.paths["/tenants"]?.get);assert.equal(spec.paths["/tenants"]?.post,undefined);assert.equal(spec.paths["/commerce/provision"]?.post?.["x-permission"],"commerce:provision")});
test("documents invitation acceptance",()=>{assert.ok(spec.paths["/invitations/accept"]?.post);assert.ok(spec.paths["/invitations/accept"].post.responses["403"])});
test("write operations declare permissions and auth errors",()=>{for(const path of ["/setup","/hcm","/performance","/payroll","/workforce","/management-reports"]){const post=spec.paths[path].post;assert.ok(post["x-permission"]);assert.ok(post.responses["401"]);assert.ok(post.responses["403"])}});
test("HCM read and write contracts declare sensitive-data permissions",()=>{assert.equal(spec.paths["/hcm"].get["x-permission"],"hcm:read");assert.equal(spec.paths["/hcm"].post["x-permission"],"hcm:write")});
test("Payroll reads including payslips require sensitive-data permission",()=>{assert.equal(spec.paths["/payroll"].get["x-permission"],"payroll:read");assert.equal(spec.paths["/payroll"].post["x-permission"],"payroll:write")});
test("workflow inbox publishes its read permission",()=>{assert.equal(spec.paths["/workflow"].get["x-permission"],"workflow:read")});
test("performance actions publish read and write permissions",()=>{assert.equal(spec.paths["/actions"].get["x-permission"],"action:read");assert.equal(spec.paths["/actions"].post["x-permission"],"action:write")});
test("forecast scenarios publish explicit permissions",()=>{assert.equal(spec.paths["/scenarios"].get["x-permission"],"scenario:read");assert.equal(spec.paths["/scenarios"].post["x-permission"],"scenario:write")});
