import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const page=fs.readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8");
const client=fs.readFileSync(new URL("../lib/api-client.ts",import.meta.url),"utf8");
test("browser API client propagates identity and selected tenant",()=>{assert.match(client,/Bearer \$\{token\}/);assert.match(client,/x-tenant-id/);assert.match(client,/ep_active_tenant/)});
test("portal navigation is driven by entitlements",()=>{for(const code of ["ANALYTICS_REPORTING","FINANCE_FP&A","HCM","PAYROLL","WORKFORCE_PLANNING","CORE"])assert.match(page,new RegExp(code));assert.match(page,/sessao\.modules\.includes/)});
test("contracted modules expose governed submodules and documents",()=>{assert.match(page,/const moduleCatalog/);assert.match(page,/document:true/);assert.match(page,/Em preparação/);assert.match(page,/MÓDULOS CONTRATADOS/)});
test("portal no longer creates tenants outside commerce",()=>{assert.doesNotMatch(page,/api\/v1\/tenants/);assert.doesNotMatch(page,/Criar nova empresa/)});
test("people workspace uses the audited HCM contract API",()=>{assert.match(page,/function PeopleWorkspace/);assert.match(page,/api\/v1\/hcm/);assert.match(page,/activateContract/);assert.match(page,/endContract/)});
test("new tenants are guided by real onboarding state without illustrative company data",()=>{assert.match(page,/TenantOnboarding/);assert.match(page,/body\.onboarding\?\.complete/);assert.doesNotMatch(page,/Ana Manuel/);assert.doesNotMatch(page,/8,42 M USD/)});
test("portal exposes deterministic readiness and next action per engine",()=>{assert.match(page,/function EngineReadiness/);assert.match(page,/api\/v1\/readiness/);assert.match(page,/Preparação dos motores/);assert.match(page,/Próxima ação/)});
test("payroll documents are issued and opened from the real payroll workspace",()=>{assert.match(page,/issuePayslips/);assert.match(page,/Documentos salariais emitidos/);assert.match(page,/Hash SHA-256/);assert.doesNotMatch(page,/Payslips",future:true/)});
test("payment batches are operational and no longer marked future",()=>{assert.match(page,/prepararLote/);assert.match(page,/transitarLote/);assert.match(page,/Lotes reconciliados e aprovados/);assert.doesNotMatch(page,/label:"Payment batches",future:true/)});
test("absence management is a functional governed HCM workspace",()=>{assert.match(page,/AbsenceWorkspace/);assert.match(page,/Ausências com saldo e decisão controlada/);assert.match(page,/decideAbsence/);assert.doesNotMatch(page,/label:"Assiduidade e ausências",future:true/)});
test("workflow is a real cross-engine decision inbox",()=>{assert.match(page,/WorkflowInbox/);assert.match(page,/Decisões pendentes num único lugar/);assert.match(page,/Abrir origem/);assert.doesNotMatch(page,/label:"Tarefas e aprovações",future:true/)});
test("performance action plans are operational and evidence governed",()=>{assert.match(page,/ActionPlans/);assert.match(page,/Transformar explicação em responsabilidade/);assert.match(page,/completion_evidence/);assert.doesNotMatch(page,/label:"Planos de ação",future:true/)});
test("forecast and scenarios are a functional FP&A workspace",()=>{assert.match(page,/ScenariosWorkspace/);assert.match(page,/Antecipar resultados sem alterar o Actual/);assert.match(page,/approvePlanningVersion/);assert.doesNotMatch(page,/label:"Forecast e cenários",future:true/)});
test("performance goals are measurable and check-in governed",()=>{assert.match(page,/GoalsWorkspace/);assert.match(page,/Objetivos mensuráveis, progresso verificável/);assert.match(page,/goalCheckin/);assert.doesNotMatch(page,/label:"Objetivos",future:true/)});
