"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api-client";
import "./attendance.css";
type Data={shifts:Array<any>;employees:Array<any>;assignments:Array<any>;entries:Array<any>;timesheets:Array<any>};
const empty:Data={shifts:[],employees:[],assignments:[],entries:[],timesheets:[]};
const hm=(v:number|null)=>v==null?"—":`${Math.floor(v/60)}h ${v%60}m`;
export function AttendanceWorkspace(){
 const [data,setData]=useState<Data>(empty),[view,setView]=useState("Marcações"),[modal,setModal]=useState(""),[context,setContext]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=()=>apiFetch("/api/v1/attendance").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 async function command(payload:Record<string,string>){setBusy(true);setError("");const r=await apiFetch("/api/v1/attendance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();setBusy(false);if(!r.ok){setError(b.error);return}setData(b);setModal("");setContext("")}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();await command({type:modal,entryId:context,timesheetId:context,...Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>})}
 const open=data.entries.filter(x=>!x.clock_out).length,extra=data.entries.reduce((a,x)=>a+Number(x.overtime_minutes||0),0),pending=data.timesheets.filter(x=>x.status==="Submetido").length;
 return <section className="attendance"><header><div><span>HCM · TIME & ATTENDANCE</span><h1>Tempo certo, custo explicável</h1><p>Turnos configuráveis, marcações rastreáveis e horas extraordinárias aprovadas antes do Payroll.</p></div><button className="primario" onClick={()=>setModal("clockIn")}>＋ Registar entrada</button></header>
 <section className="attendance-kpis"><article><span>Marcações abertas</span><strong>{open}</strong><small>Aguardam saída</small></article><article><span>Horas extraordinárias</span><strong>{hm(extra)}</strong><small>Cálculo determinístico</small></article><article><span>Timesheets pendentes</span><strong>{pending}</strong><small>Maker-checker</small></article><article><span>Turnos ativos</span><strong>{data.shifts.filter(x=>x.status==="Ativo").length}</strong><small>Sem regra laboral hardcoded</small></article></section>
 <nav className="attendance-tabs">{["Marcações","Timesheets","Configuração"].map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}>{x}</button>)}</nav>{error&&<p className="attendance-error">{error}</p>}
 {view==="Marcações"?<article className="cartao attendance-list"><div className="cab"><div><span>REGISTO DIÁRIO</span><h2>Entradas, saídas e exceções</h2></div></div>{data.entries.map(x=><section key={x.id}><span><b>{x.employee_name}</b><small>{x.employee_number} · {x.work_date}</small></span><p><b>{x.clock_in} → {x.clock_out||"Em curso"}</b><small>{hm(x.worked_minutes)} trabalhados · {hm(x.scheduled_minutes)} previstos</small></p><em>{x.exception_code||(!x.clock_out?"Aberta":"Regular")}</em>{!x.clock_out&&<button onClick={()=>{setContext(x.id);setModal("clockOut")}}>Registar saída</button>}</section>)}</article>:view==="Timesheets"?<article className="cartao attendance-list"><div className="cab"><div><span>FOLHAS DE TEMPO</span><h2>Consolidação e aprovação mensal</h2></div><button onClick={()=>setModal("buildTimesheet")}>＋ Consolidar</button></div>{data.timesheets.map(x=><section key={x.id}><span><b>{x.employee_name}</b><small>{x.employee_number} · {x.period} · {x.entry_count} dias</small></span><p><b>{hm(x.worked_minutes)} trabalhados</b><small>{hm(x.overtime_minutes)} extraordinários · hash {String(x.source_hash).slice(0,10)}</small></p><em>{x.status}</em><nav>{x.status==="Rascunho"&&<button onClick={()=>command({type:"submitTimesheet",timesheetId:x.id})}>Submeter</button>}{x.status==="Submetido"&&<button onClick={()=>{setContext(x.id);setModal("decideTimesheet")}}>Decidir</button>}</nav></section>)}</article>:<div className="attendance-config"><article className="cartao attendance-list"><div className="cab"><div><span>TURNOS</span><h2>Jornadas configuráveis</h2></div><button onClick={()=>setModal("createShift")}>＋ Novo turno</button></div>{data.shifts.map(x=><section key={x.id}><span><b>{x.code} · {x.name}</b><small>{String(Math.floor(x.start_minute/60)).padStart(2,"0")}:{String(x.start_minute%60).padStart(2,"0")} → {String(Math.floor(x.end_minute/60)).padStart(2,"0")}:{String(x.end_minute%60).padStart(2,"0")}</small></span><p><b>{hm(x.scheduled_minutes)}</b><small>Pausa {hm(x.break_minutes)}</small></p><em>{x.status}</em></section>)}</article><article className="cartao attendance-list"><div className="cab"><div><span>ATRIBUIÇÕES</span><h2>Turno por colaborador</h2></div><button onClick={()=>setModal("assignShift")}>＋ Atribuir</button></div>{data.assignments.map(x=><section key={x.id}><span><b>{x.employee_name}</b><small>{x.employee_number}</small></span><p><b>{x.shift_code} · {x.shift_name}</b><small>Desde {x.effective_from}</small></p><em>{x.status}</em></section>)}</article></div>}
 {modal&&<div className="modal-fundo"><form className="modal-card" onSubmit={submit}><button type="button" className="fechar" onClick={()=>setModal("")}>×</button><span>ASSIDUIDADE GOVERNADA</span><h2>{({createShift:"Novo turno",assignShift:"Atribuir turno",clockIn:"Registar entrada",clockOut:"Registar saída",buildTimesheet:"Consolidar timesheet",decideTimesheet:"Decidir timesheet"} as Record<string,string>)[modal]}</h2>{["assignShift","clockIn","buildTimesheet"].includes(modal)&&<label>Colaborador<select name="employeeId" required><option value="">Selecionar</option>{data.employees.map(x=><option key={x.id} value={x.id}>{x.employee_number} · {x.employee_name}</option>)}</select></label>}{modal==="createShift"&&<><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><div className="duplo"><label>Início<input name="startTime" type="time" required/></label><label>Fim<input name="endTime" type="time" required/></label></div><label>Pausa (minutos)<input name="breakMinutes" type="number" min="0" defaultValue="60"/></label></>}{modal==="assignShift"&&<><label>Turno<select name="shiftId" required><option value="">Selecionar</option>{data.shifts.filter(x=>x.status==="Ativo").map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Vigência<input name="effectiveFrom" type="date" required/></label></>}{modal==="clockIn"&&<><div className="duplo"><label>Data<input name="workDate" type="date" required/></label><label>Entrada<input name="clockIn" type="time" required/></label></div><label>Origem<select name="source"><option>Manual</option><option>Importação</option><option>Terminal</option></select></label><label>Nota<input name="note"/></label></>}{modal==="clockOut"&&<label>Saída<input name="clockOut" type="time" required/></label>}{modal==="buildTimesheet"&&<label>Período<input name="period" type="month" required/></label>}{modal==="decideTimesheet"&&<><label>Decisão<select name="decision"><option>Aprovado</option><option>Rejeitado</option></select></label><label>Nota de decisão<textarea name="decisionNote"/></label></>}<button className="primario" disabled={busy}>{busy?"A processar…":"Confirmar"}</button></form></div>}</section>
}
