"use client";
import{useEffect,useState}from"react";import{apiFetch}from"../lib/api-client";import type{PlatformLocale}from"../lib/platform-i18n";import{usePlatformLocale}from"./use-platform-locale";import"./demo-portfolio.css";
const copy:Record<PlatformLocale,Record<string,string>>={
pt:{eyebrow:"EMPRESA DEMONSTRATIVA COMPLETA",loading:"A preencher todos os módulos…",installed:"Demonstração Enterprise instalada",error:"Instalação requer atenção",ready:"A preparar demonstração",retry:"Tentar novamente",modules:"módulos",records:"registos",failure:"Não foi possível instalar.",scope:"Finance, FP&A, RH, Payroll, Workforce, Performance, Analytics, Workflow e Integrações."},
en:{eyebrow:"COMPLETE DEMONSTRATION COMPANY",loading:"Populating all modules…",installed:"Enterprise demonstration installed",error:"Installation requires attention",ready:"Preparing demonstration",retry:"Try again",modules:"modules",records:"records",failure:"Installation could not be completed.",scope:"Finance, FP&A, HR, Payroll, Workforce, Performance, Analytics, Workflow and Integrations."},
es:{eyebrow:"EMPRESA DEMOSTRATIVA COMPLETA",loading:"Completando todos los módulos…",installed:"Demostración Enterprise instalada",error:"La instalación requiere atención",ready:"Preparando demostración",retry:"Intentar de nuevo",modules:"módulos",records:"registros",failure:"No se pudo completar la instalación.",scope:"Finanzas, FP&A, RR. HH., Nómina, Plantilla, Rendimiento, Analítica, Flujos e Integraciones."},
fr:{eyebrow:"ENTREPRISE DE DÉMONSTRATION COMPLÈTE",loading:"Chargement de tous les modules…",installed:"Démonstration Enterprise installée",error:"L’installation nécessite une attention",ready:"Préparation de la démonstration",retry:"Réessayer",modules:"modules",records:"enregistrements",failure:"L’installation n’a pas pu aboutir.",scope:"Finance, FP&A, RH, Paie, Effectifs, Performance, Analytique, Workflow et Intégrations."},
ru:{eyebrow:"ПОЛНАЯ ДЕМОНСТРАЦИОННАЯ КОМПАНИЯ",loading:"Заполнение всех модулей…",installed:"Демонстрационная среда Enterprise установлена",error:"Установка требует внимания",ready:"Подготовка демонстрации",retry:"Повторить",modules:"модулей",records:"записей",failure:"Не удалось завершить установку.",scope:"Финансы, FP&A, HR, расчёт зарплаты, персонал, эффективность, аналитика, процессы и интеграции."}};
export function DemoPortfolioLoader({eligible}:{eligible:boolean}){const locale=usePlatformLocale(),t=copy[locale],[state,setState]=useState<"checking"|"ready"|"loading"|"installed"|"error">(eligible?"checking":"ready"),[counts,setCounts]=useState<{modules:number;records:number;version:string}|null>(null);useEffect(()=>{if(!eligible)return;apiFetch("/api/v1/demo-portfolio").then(r=>r.json()).then(x=>{if(x.installed){setState("installed");setCounts({modules:x.installation?.module_count||9,records:x.installation?.record_count||150,version:x.installation?.dataset_version||"DEMO-ENTERPRISE-2026.2"})}else install()}).catch(()=>setState("error"))},[eligible]);async function install(){setState("loading");const r=await apiFetch("/api/v1/demo-portfolio",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"install-enterprise"})}),b=await r.json();if(!r.ok){setState("error");return}setState("installed");setCounts({modules:b.modules||9,records:b.records||150,version:b.datasetVersion||"DEMO-ENTERPRISE-2026.2"});setTimeout(()=>window.location.reload(),900)}if(!eligible)return null;const title=state==="loading"?t.loading:state==="installed"?t.installed:state==="error"?t.error:t.ready,detail=counts?`${counts.modules} ${t.modules} · ${counts.records} ${t.records} · ${counts.version}`:state==="error"?t.failure:t.scope;return <section className={`demo-loader ${state}`}><i>{state==="installed"?"✓":state==="error"?"!":"◇"}</i><span><small>{t.eyebrow}</small><b>{title}</b><p>{detail}</p></span>{state==="error"&&<button onClick={install}>{t.retry}</button>}</section>}
