"use client";
import { useMemo, useState } from "react";
import "./finance-suite.css";

const packages = ["Cockpit CFO","Demonstrações","Performance","Desvios","Tesouraria","Working Capital","Rentabilidade","Management Pack"] as const;
type View=(typeof packages)[number];
const months=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago"];
const actual=[318,334,351,362,389,407,421,438], budget=[310,326,343,365,380,398,415,432], forecast=[318,334,351,362,389,407,426,449];
const money=(n:number)=>`${new Intl.NumberFormat("pt-PT",{maximumFractionDigits:1}).format(n)} M AOA`;
const pct=(n:number)=>`${n>0?"+":""}${n.toFixed(1)}%`;

export function FinanceSuite({initialView="Cockpit CFO"}:{initialView?:View}){
 const [view,setView]=useState<View>(initialView),[period,setPeriod]=useState("Agosto 2026"),[scenario,setScenario]=useState("Actual vs Budget"),[entity,setEntity]=useState("Grupo consolidado"),[detail,setDetail]=useState("");
 const variance=actual[7]-budget[7], variancePct=variance/budget[7]*100;
 const exportPack=()=>{const content=`MANAGEMENT PACK | ${entity} | ${period}\nReceita: ${money(438)}\nEBITDA: ${money(82.4)}\nResultado líquido: ${money(49.6)}\nCaixa: ${money(214.8)}\nDesvio receita: ${money(variance)} (${pct(variancePct)})\n\nConclusão: crescimento acima do orçamento, com pressão de margem logística e risco de concentração de clientes.`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/plain;charset=utf-8"}));a.download=`management-pack-${period.toLowerCase().replaceAll(" ","-")}.txt`;a.click();URL.revokeObjectURL(a.href)};
 return <section className="finance-suite">
  <header className="finance-hero"><div><span>FINANCE PERFORMANCE & DECISION MANAGEMENT</span><h1>Centro de decisão do CFO</h1><p>Resultado, liquidez, risco e ação numa visão financeira integrada e auditável.</p></div><div className="finance-controls"><label>Empresa<select value={entity} onChange={e=>setEntity(e.target.value)}><option>Grupo consolidado</option><option>Operações Angola</option><option>Serviços Corporativos</option></select></label><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}><option>Agosto 2026</option><option>Julho 2026</option><option>2.º Trimestre 2026</option></select></label><label>Comparação<select value={scenario} onChange={e=>setScenario(e.target.value)}><option>Actual vs Budget</option><option>Actual vs Forecast</option><option>Actual vs Ano anterior</option></select></label><button onClick={exportPack}>Exportar Pack ↓</button></div></header>
  <nav className="finance-tabs" aria-label="Pacotes financeiros">{packages.map((x,i)=><button key={x} className={view===x?"active":""} onClick={()=>{setView(x);setDetail("")}}><i>{i+1}</i>{x}</button>)}</nav>
  {view==="Cockpit CFO"&&<Cockpit onOpen={setView} onDetail={setDetail}/>} 
  {view==="Demonstrações"&&<Statements/>}
  {view==="Performance"&&<Performance/>}
  {view==="Desvios"&&<Bridges/>}
  {view==="Tesouraria"&&<Treasury/>}
  {view==="Working Capital"&&<WorkingCapital/>}
  {view==="Rentabilidade"&&<Profitability/>}
  {view==="Management Pack"&&<ManagementPack onExport={exportPack}/>} 
  {detail&&<div className="finance-drawer"><button onClick={()=>setDetail("")}>×</button><small>DRILL-THROUGH · EVIDÊNCIA</small><h2>{detail}</h2><p>Valor reconciliado com a origem, dimensão organizacional, período e versão selecionados.</p><table><tbody><tr><th>Operações Angola</th><td>{money(288.4)}</td><td>65,8%</td></tr><tr><th>Serviços Corporativos</th><td>{money(91.7)}</td><td>20,9%</td></tr><tr><th>Outras unidades</th><td>{money(57.9)}</td><td>13,3%</td></tr></tbody></table><footer>Fonte: Actual aprovado · Mapping FIN-REV-01 · Atualizado no fecho de Agosto</footer></div>}
 </section>
}

function Cockpit({onOpen,onDetail}:{onOpen:(x:View)=>void;onDetail:(x:string)=>void}){const kpis=[["Receita",438,"+1,4%","Acima do Budget"],["EBITDA",82.4,"−3,2%","Pressão logística"],["Resultado líquido",49.6,"+6,8%","Juros inferiores"],["Caixa disponível",214.8,"+18,5%","Runway: 7,4 meses"]] as const;return <><section className="finance-kpis">{kpis.map((x,i)=><article key={x[0]} onClick={()=>onDetail(x[0])}><span>{x[0]}</span><strong>{money(x[1])}</strong><em className={i===1?"bad":"good"}>{x[2]}</em><small>{x[3]} · abrir detalhe →</small></article>)}</section><div className="finance-grid"><article className="finance-card span2"><CardTitle tag="TENDÊNCIA" title="Receita · Actual, Budget e Forecast" action="Abrir performance" onClick={()=>onOpen("Performance")}/><TrendChart/></article><article className="finance-card"><CardTitle tag="LIQUIDEZ" title="Previsão de caixa · 13 semanas" action="Abrir tesouraria" onClick={()=>onOpen("Tesouraria")}/><div className="cash-ring"><strong>214,8</strong><span>M AOA disponíveis</span></div><dl><div><dt>Mínimo projetado</dt><dd>126,4 M</dd></div><div><dt>Buffer de liquidez</dt><dd>2,1×</dd></div></dl></article><article className="finance-card"><CardTitle tag="EXPLICAÇÃO" title="O que moveu o EBITDA" action="Ver bridge" onClick={()=>onOpen("Desvios")}/><ul className="driver-list"><li><b>Preço e mix</b><em className="good">+12,6 M</em></li><li><b>Volume</b><em className="good">+7,4 M</em></li><li><b>Logística</b><em className="bad">−14,8 M</em></li><li><b>Câmbio</b><em className="bad">−8,1 M</em></li></ul></article><article className="finance-card span2"><CardTitle tag="AÇÃO" title="Prioridades financeiras" action="Management Pack" onClick={()=>onOpen("Management Pack")}/><div className="action-list"><span><i className="high">Alta</i><b>Renegociar prazo dos 3 maiores clientes</b><em>Responsável: Tesouraria · 5 dias</em></span><span><i>Média</i><b>Rever contrato de transporte</b><em>Responsável: Operações · 12 dias</em></span><span><i>Monitorizar</i><b>Covenant dívida líquida/EBITDA</b><em>Margem atual: 0,7×</em></span></div></article></div></>}
function CardTitle({tag,title,action,onClick}:{tag:string;title:string;action?:string;onClick?:()=>void}){return <header className="card-title"><div><span>{tag}</span><h2>{title}</h2></div>{action&&<button onClick={onClick}>{action} →</button>}</header>}
function TrendChart(){const max=470;return <div className="trend-chart"><div className="chart-legend"><span><i className="a"/>Actual</span><span><i className="b"/>Budget</span><span><i className="f"/>Forecast</span></div><div className="bars">{months.map((m,i)=><div key={m}><section><i className="b" style={{height:`${budget[i]/max*100}%`}}/><i className="a" style={{height:`${actual[i]/max*100}%`}}/><i className="f" style={{height:`${forecast[i]/max*100}%`}}/></section><small>{m}</small></div>)}</div></div>}
function Statements(){const rows=[["Receita líquida",438,432,406],["Custos diretos",-246,-231,-224],["Margem bruta",192,201,182],["OPEX",-109.6,-116,-108],["EBITDA",82.4,85,74],["Resultado líquido",49.6,46.4,41.2]];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="DEMONSTRAÇÕES INTEGRADAS" title="Demonstração de Resultados"/><FinanceTable rows={rows}/></article><article className="finance-card"><CardTitle tag="BALANÇO" title="Posição financeira"/><MetricRows rows={[["Ativos",1284],["Passivos",716],["Capital próprio",568],["Dívida líquida",301]]}/></article><article className="finance-card"><CardTitle tag="FLUXO DE CAIXA" title="Reconciliação de caixa"/><MetricRows rows={[["Operacional",96.8],["Investimento",-42.1],["Financiamento",18.4],["Variação líquida",73.1]]}/></article></div>}
function FinanceTable({rows}:{rows:(string|number)[][]}){return <div className="finance-table"><table><thead><tr><th>Linha</th><th>Actual</th><th>Budget</th><th>Ano anterior</th><th>Var. Budget</th></tr></thead><tbody>{rows.map(r=><tr key={String(r[0])}><th>{r[0]}</th><td>{money(Number(r[1]))}</td><td>{money(Number(r[2]))}</td><td>{money(Number(r[3]))}</td><td className={Number(r[1])-Number(r[2])>=0?"good":"bad"}>{money(Number(r[1])-Number(r[2]))}</td></tr>)}</tbody></table></div>}
function MetricRows({rows}:{rows:[string,number][]}){return <div className="metric-rows">{rows.map(x=><div key={x[0]}><span>{x[0]}</span><b>{money(x[1])}</b></div>)}</div>}
function Performance(){return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="ACTUAL · BUDGET · FORECAST" title="Performance mensal e previsão de fecho"/><TrendChart/></article><article className="finance-card"><CardTitle tag="FORECAST ACCURACY" title="Qualidade da previsão"/><div className="score"><strong>94,2%</strong><span>+2,8 p.p. em 3 meses</span></div><MetricRows rows={[["Receita FY",5284],["EBITDA FY",988],["Caixa final",236]]}/></article><article className="finance-card"><CardTitle tag="DRIVERS" title="Premissas críticas"/><ul className="driver-list"><li><b>Volume</b><em>+4,2%</em></li><li><b>Preço médio</b><em>+2,6%</em></li><li><b>Câmbio médio</b><em>1 012 AOA</em></li><li><b>Inflação</b><em>18,4%</em></li></ul></article></div>}
function Bridges(){const items:[[string,number,string],...Array<[string,number,string]>]=[["EBITDA Budget",85,"base"],["Preço",9.8,"up"],["Volume",5.7,"up"],["Mix",-2.9,"down"],["Logística",-8.6,"down"],["Câmbio",-6.6,"down"],["EBITDA Actual",82.4,"total"]];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="VARIANCE BRIDGE" title="Da expectativa ao resultado"/><div className="bridge">{items.map(x=><div key={x[0]}><span>{x[0]}</span><i className={x[2]} style={{height:`${Math.max(22,Math.abs(x[1])*2.1)}px`}}/><b>{x[1]>0?"+":""}{x[1]} M</b></div>)}</div></article><article className="finance-card"><CardTitle tag="CAUSAS" title="Classificação do desvio"/><MetricRows rows={[["Controlável",-9.1],["Não controlável",-4.6],["Recorrente",-5.8],["Não recorrente",-7.9]]}/></article><article className="finance-card"><CardTitle tag="IMPACTO" title="Perspetiva anual"/><div className="score warning"><strong>−38,6 M</strong><span>Risco EBITDA se nenhuma ação for executada</span></div></article></div>}
function Treasury(){const weeks=[214,202,187,192,174,158,146,132,126,139,151,168,183];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="13-WEEK CASH FORECAST" title="Liquidez projetada"/><div className="line-bars">{weeks.map((x,i)=><div key={i}><i style={{height:`${x/2.4}px`}}/><b>{x}</b><small>S{i+1}</small></div>)}</div></article><article className="finance-card"><CardTitle tag="POSIÇÃO BANCÁRIA" title="Caixa por moeda"/><MetricRows rows={[["AOA",124.6],["USD",76.2],["EUR",14.0]]}/></article><article className="finance-card"><CardTitle tag="DÍVIDA" title="Financiamento e covenants"/><MetricRows rows={[["Dívida bruta",515.8],["Dívida líquida",301],["Serviço 90 dias",72.5]]}/><p className="status-note good">✓ Covenants dentro do limite · DSCR 1,42×</p></article></div>}
function WorkingCapital(){return <div className="finance-grid"><article className="finance-card"><CardTitle tag="CICLO DE CAIXA" title="Cash Conversion Cycle"/><div className="score"><strong>48 dias</strong><span>−6 dias vs trimestre anterior</span></div><MetricRows rows={[["DSO · 62 dias",286],["DIO · 31 dias",144],["DPO · 45 dias",209]]}/></article><article className="finance-card span2"><CardTitle tag="AGING" title="Contas a receber"/><div className="aging">{[["Não vencido",184,64],["1–30 dias",58,20],["31–60 dias",27,9],["61–90 dias",12,4],["> 90 dias",8,3]].map(x=><div key={x[0]}><span>{x[0]}</span><section><i style={{width:`${x[2]}%`}}/></section><b>{money(x[1])}</b></div>)}</div></article><article className="finance-card span2"><CardTitle tag="OPORTUNIDADE" title="Libertação potencial de caixa"/><div className="opportunity"><strong>28,4 M AOA</strong><p>Reduzindo o DSO de 62 para 55 dias através de cobrança priorizada nos 10 maiores saldos.</p><button>Converter em plano de ação →</button></div></article></div>}
function Profitability(){const rows=[["Serviços Enterprise",188,34.8,28.1],["Operações",142,21.4,17.9],["Projetos",71,18.6,12.8],["Suporte",37,9.2,6.1]];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="RENTABILIDADE MULTIDIMENSIONAL" title="Margem por unidade de negócio"/><div className="finance-table"><table><thead><tr><th>Unidade</th><th>Receita</th><th>Margem bruta</th><th>Margem contribuição</th><th>Sinal</th></tr></thead><tbody>{rows.map(x=><tr key={String(x[0])}><th>{x[0]}</th><td>{money(Number(x[1]))}</td><td>{x[2]}%</td><td>{x[3]}%</td><td><em className={Number(x[3])>10?"good":"bad"}>{Number(x[3])>10?"Criador de valor":"Rever"}</em></td></tr>)}</tbody></table></div></article><article className="finance-card"><CardTitle tag="UNIT ECONOMICS" title="Economia por cliente"/><MetricRows rows={[["Receita média",12.8],["Cost-to-serve",8.1],["Contribuição",4.7]]}/></article><article className="finance-card"><CardTitle tag="CONCENTRAÇÃO" title="Risco comercial"/><div className="score warning"><strong>38%</strong><span>da receita nos 3 maiores clientes</span></div><p className="status-note bad">! Acima do limite interno de 35%</p></article></div>}
function ManagementPack({onExport}:{onExport:()=>void}){return <div className="pack"><header><div><small>BOARD & MANAGEMENT REPORTING</small><h2>Management Pack · Agosto 2026</h2><p>Grupo consolidado · Actual vs Budget · Versão aprovada</p></div><button onClick={onExport}>Download do relatório ↓</button></header><section><article><span>01 · RESULTADO</span><h3>Crescimento acima do plano, com pressão operacional sobre a margem</h3><p>A receita atingiu 438 M AOA, 1,4% acima do orçamento. O EBITDA ficou 3,2% abaixo devido a custos logísticos e impacto cambial.</p></article><article><span>02 · COMPARAÇÃO E CAUSA</span><h3>Preço e volume compensaram parcialmente custos externos</h3><p>Preço, mix e volume contribuíram positivamente com 12,6 M AOA; logística e câmbio retiraram 14,8 M AOA.</p></article><article><span>03 · IMPACTO E PERSPETIVA</span><h3>Liquidez protegida, mas o risco anual exige resposta</h3><p>O caixa mínimo projetado é 126,4 M AOA. Sem ações, o risco anual sobre EBITDA pode alcançar 38,6 M AOA.</p></article><article><span>04 · RECOMENDAÇÃO</span><h3>Atuar sobre cobrança, logística e exposição cambial</h3><ol><li>Reduzir DSO para 55 dias.</li><li>Renegociar contrato logístico.</li><li>Proteger 60% da exposição cambial prevista.</li></ol></article></section><footer><b>Governação:</b> valores determinísticos · evidência preservada · narrativa sujeita a aprovação do CFO</footer></div>}
