"use client";
import { useMemo, useState } from "react";
import type { PlatformLocale } from "../lib/platform-i18n";
import { usePlatformLocale } from "./use-platform-locale";
import "./finance-suite.css";

const fc:Record<PlatformLocale,Record<string,string>>={
pt:{title:"Centro de decisão do CFO",intro:"Resultado, liquidez, risco e ação numa visão financeira integrada e auditável.",company:"Empresa",period:"Período",comparison:"Comparação",group:"Grupo consolidado",angola:"Operações Angola",corporate:"Serviços Corporativos",aug:"Agosto 2026",jul:"Julho 2026",quarter:"2.º Trimestre 2026",previous:"Actual vs Ano anterior",export:"Exportar Pack ↓",tabs:"Pacotes financeiros",statements:"Demonstrações",performance:"Performance",variance:"Desvios",treasury:"Tesouraria",profitability:"Rentabilidade",drawer:"DRILL-THROUGH · EVIDÊNCIA",reconciled:"Valor reconciliado com a origem, dimensão organizacional, período e versão selecionados.",other:"Outras unidades",source:"Fonte: Actual aprovado · Mapping FIN-REV-01 · Atualizado no fecho de Agosto",revenue:"Receita",above:"Acima do Budget",ebitda:"EBITDA",pressure:"Pressão logística",net:"Resultado líquido",interest:"Juros inferiores",cash:"Caixa disponível",runway:"Runway: 7,4 meses",detail:"abrir detalhe →",trend:"TENDÊNCIA",trendTitle:"Receita · Actual, Budget e Forecast",openPerformance:"Abrir performance",liquidity:"LIQUIDEZ",cashForecast:"Previsão de caixa · 13 semanas",openTreasury:"Abrir tesouraria",available:"M AOA disponíveis",minimum:"Mínimo projetado",buffer:"Buffer de liquidez",explanation:"EXPLICAÇÃO",ebitdaMove:"O que moveu o EBITDA",bridge:"Ver bridge",priceMix:"Preço e mix",volume:"Volume",logistics:"Logística",fx:"Câmbio",action:"AÇÃO",priorities:"Prioridades financeiras",pack:"Management Pack",high:"Alta",medium:"Média",monitor:"Monitorizar",renegotiate:"Renegociar prazo dos 3 maiores clientes",ownerTreasury:"Responsável: Tesouraria · 5 dias",reviewTransport:"Rever contrato de transporte",ownerOps:"Responsável: Operações · 12 dias",covenant:"Covenant dívida líquida/EBITDA",margin:"Margem atual: 0,7×"},
en:{title:"CFO decision centre",intro:"Results, liquidity, risk and action in an integrated, auditable financial view.",company:"Company",period:"Period",comparison:"Comparison",group:"Consolidated group",angola:"Angola operations",corporate:"Corporate services",aug:"August 2026",jul:"July 2026",quarter:"Q2 2026",previous:"Actual vs prior year",export:"Export pack ↓",tabs:"Financial packages",statements:"Statements",performance:"Performance",variance:"Variances",treasury:"Treasury",profitability:"Profitability",drawer:"DRILL-THROUGH · EVIDENCE",reconciled:"Value reconciled to source, organisational dimension, period and selected version.",other:"Other units",source:"Source: approved Actual · Mapping FIN-REV-01 · Updated at August close",revenue:"Revenue",above:"Above Budget",ebitda:"EBITDA",pressure:"Logistics pressure",net:"Net income",interest:"Lower interest",cash:"Available cash",runway:"Runway: 7.4 months",detail:"open detail →",trend:"TREND",trendTitle:"Revenue · Actual, Budget and Forecast",openPerformance:"Open performance",liquidity:"LIQUIDITY",cashForecast:"13-week cash forecast",openTreasury:"Open treasury",available:"M AOA available",minimum:"Projected minimum",buffer:"Liquidity buffer",explanation:"EXPLANATION",ebitdaMove:"What moved EBITDA",bridge:"View bridge",priceMix:"Price and mix",volume:"Volume",logistics:"Logistics",fx:"Foreign exchange",action:"ACTION",priorities:"Financial priorities",pack:"Management Pack",high:"High",medium:"Medium",monitor:"Monitor",renegotiate:"Renegotiate terms with the 3 largest customers",ownerTreasury:"Owner: Treasury · 5 days",reviewTransport:"Review transport contract",ownerOps:"Owner: Operations · 12 days",covenant:"Net debt/EBITDA covenant",margin:"Current headroom: 0.7×"},
es:{title:"Centro de decisión del CFO",intro:"Resultados, liquidez, riesgo y acción en una visión financiera integrada y auditable.",company:"Empresa",period:"Período",comparison:"Comparación",group:"Grupo consolidado",angola:"Operaciones Angola",corporate:"Servicios corporativos",aug:"Agosto de 2026",jul:"Julio de 2026",quarter:"2.º trimestre de 2026",previous:"Real vs año anterior",export:"Exportar paquete ↓",tabs:"Paquetes financieros",statements:"Estados financieros",performance:"Rendimiento",variance:"Desviaciones",treasury:"Tesorería",profitability:"Rentabilidad",drawer:"DETALLE · EVIDENCIA",reconciled:"Valor conciliado con el origen, dimensión organizativa, período y versión seleccionados.",other:"Otras unidades",source:"Fuente: Real aprobado · Mapeo FIN-REV-01 · Actualizado al cierre de agosto",revenue:"Ingresos",above:"Sobre Presupuesto",ebitda:"EBITDA",pressure:"Presión logística",net:"Resultado neto",interest:"Menores intereses",cash:"Caja disponible",runway:"Autonomía: 7,4 meses",detail:"abrir detalle →",trend:"TENDENCIA",trendTitle:"Ingresos · Real, Presupuesto y Previsión",openPerformance:"Abrir rendimiento",liquidity:"LIQUIDEZ",cashForecast:"Previsión de caja · 13 semanas",openTreasury:"Abrir tesorería",available:"M AOA disponibles",minimum:"Mínimo proyectado",buffer:"Colchón de liquidez",explanation:"EXPLICACIÓN",ebitdaMove:"Qué impulsó el EBITDA",bridge:"Ver puente",priceMix:"Precio y mix",volume:"Volumen",logistics:"Logística",fx:"Tipo de cambio",action:"ACCIÓN",priorities:"Prioridades financieras",pack:"Paquete de gestión",high:"Alta",medium:"Media",monitor:"Supervisar",renegotiate:"Renegociar el plazo de los 3 mayores clientes",ownerTreasury:"Responsable: Tesorería · 5 días",reviewTransport:"Revisar contrato de transporte",ownerOps:"Responsable: Operaciones · 12 días",covenant:"Covenant deuda neta/EBITDA",margin:"Margen actual: 0,7×"},
fr:{title:"Centre de décision du CFO",intro:"Résultat, liquidité, risque et action dans une vue financière intégrée et auditable.",company:"Entreprise",period:"Période",comparison:"Comparaison",group:"Groupe consolidé",angola:"Opérations Angola",corporate:"Services corporate",aug:"Août 2026",jul:"Juillet 2026",quarter:"2e trimestre 2026",previous:"Réel vs année précédente",export:"Exporter le pack ↓",tabs:"Packs financiers",statements:"États financiers",performance:"Performance",variance:"Écarts",treasury:"Trésorerie",profitability:"Rentabilité",drawer:"DRILL-THROUGH · PREUVE",reconciled:"Valeur rapprochée de la source, de la dimension organisationnelle, de la période et de la version sélectionnées.",other:"Autres unités",source:"Source : Réel approuvé · Mapping FIN-REV-01 · Mis à jour à la clôture d’août",revenue:"Chiffre d’affaires",above:"Au-dessus du budget",ebitda:"EBITDA",pressure:"Pression logistique",net:"Résultat net",interest:"Intérêts inférieurs",cash:"Trésorerie disponible",runway:"Autonomie : 7,4 mois",detail:"ouvrir le détail →",trend:"TENDANCE",trendTitle:"Chiffre d’affaires · Réel, Budget et Prévision",openPerformance:"Ouvrir la performance",liquidity:"LIQUIDITÉ",cashForecast:"Prévision de trésorerie · 13 semaines",openTreasury:"Ouvrir la trésorerie",available:"M AOA disponibles",minimum:"Minimum projeté",buffer:"Marge de liquidité",explanation:"EXPLICATION",ebitdaMove:"Facteurs de variation de l’EBITDA",bridge:"Voir le pont",priceMix:"Prix et mix",volume:"Volume",logistics:"Logistique",fx:"Change",action:"ACTION",priorities:"Priorités financières",pack:"Pack de gestion",high:"Haute",medium:"Moyenne",monitor:"Surveiller",renegotiate:"Renégocier le délai des 3 principaux clients",ownerTreasury:"Responsable : Trésorerie · 5 jours",reviewTransport:"Revoir le contrat de transport",ownerOps:"Responsable : Opérations · 12 jours",covenant:"Covenant dette nette/EBITDA",margin:"Marge actuelle : 0,7×"},
ru:{title:"Центр решений CFO",intro:"Результаты, ликвидность, риски и действия в едином контролируемом финансовом обзоре.",company:"Компания",period:"Период",comparison:"Сравнение",group:"Консолидированная группа",angola:"Операции в Анголе",corporate:"Корпоративные услуги",aug:"Август 2026",jul:"Июль 2026",quarter:"2-й квартал 2026",previous:"Факт к прошлому году",export:"Экспорт пакета ↓",tabs:"Финансовые пакеты",statements:"Отчётность",performance:"Эффективность",variance:"Отклонения",treasury:"Казначейство",profitability:"Рентабельность",drawer:"ДЕТАЛИЗАЦИЯ · ДОКАЗАТЕЛЬСТВА",reconciled:"Значение сверено с источником, организационным измерением, периодом и выбранной версией.",other:"Другие подразделения",source:"Источник: утверждённый факт · Mapping FIN-REV-01 · Обновлено при закрытии августа",revenue:"Выручка",above:"Выше бюджета",ebitda:"EBITDA",pressure:"Давление логистики",net:"Чистая прибыль",interest:"Снижение процентов",cash:"Доступные денежные средства",runway:"Запас: 7,4 месяца",detail:"открыть детали →",trend:"ТЕНДЕНЦИЯ",trendTitle:"Выручка · Факт, Бюджет и Прогноз",openPerformance:"Открыть показатели",liquidity:"ЛИКВИДНОСТЬ",cashForecast:"Прогноз денежных средств · 13 недель",openTreasury:"Открыть казначейство",available:"млн AOA доступно",minimum:"Прогнозный минимум",buffer:"Резерв ликвидности",explanation:"ОБЪЯСНЕНИЕ",ebitdaMove:"Факторы изменения EBITDA",bridge:"Открыть мост",priceMix:"Цена и структура",volume:"Объём",logistics:"Логистика",fx:"Валютный курс",action:"ДЕЙСТВИЕ",priorities:"Финансовые приоритеты",pack:"Управленческий пакет",high:"Высокий",medium:"Средний",monitor:"Контроль",renegotiate:"Пересмотреть сроки для 3 крупнейших клиентов",ownerTreasury:"Ответственный: Казначейство · 5 дней",reviewTransport:"Пересмотреть транспортный контракт",ownerOps:"Ответственный: Операции · 12 дней",covenant:"Ковенант чистый долг/EBITDA",margin:"Текущий запас: 0,7×"}};

type DeepCopy={integrated:string;income:string;incomeRows:string[];balance:string;position:string;balanceRows:string[];cashflow:string;cashReconciliation:string;cashRows:string[];line:string;actual:string;budget:string;prior:string;variance:string;performanceTitle:string;forecastQuality:string;quality:string;qualityDelta:string;forecastRows:string[];drivers:string;assumptions:string;assumptionRows:string[];months:string[]};
const fd:Record<PlatformLocale,DeepCopy>={
pt:{integrated:"DEMONSTRAÇÕES INTEGRADAS",income:"Demonstração de Resultados",incomeRows:["Receita líquida","Custos diretos","Margem bruta","OPEX","EBITDA","Resultado líquido"],balance:"BALANÇO",position:"Posição financeira",balanceRows:["Ativos","Passivos","Capital próprio","Dívida líquida"],cashflow:"FLUXO DE CAIXA",cashReconciliation:"Reconciliação de caixa",cashRows:["Operacional","Investimento","Financiamento","Variação líquida"],line:"Linha",actual:"Actual",budget:"Budget",prior:"Ano anterior",variance:"Var. Budget",performanceTitle:"Performance mensal e previsão de fecho",forecastQuality:"FORECAST ACCURACY",quality:"Qualidade da previsão",qualityDelta:"+2,8 p.p. em 3 meses",forecastRows:["Receita FY","EBITDA FY","Caixa final"],drivers:"DRIVERS",assumptions:"Premissas críticas",assumptionRows:["Volume","Preço médio","Câmbio médio","Inflação"],months:["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago"]},
en:{integrated:"INTEGRATED STATEMENTS",income:"Income statement",incomeRows:["Net revenue","Direct costs","Gross margin","OPEX","EBITDA","Net income"],balance:"BALANCE SHEET",position:"Financial position",balanceRows:["Assets","Liabilities","Equity","Net debt"],cashflow:"CASH FLOW",cashReconciliation:"Cash reconciliation",cashRows:["Operating","Investing","Financing","Net change"],line:"Line",actual:"Actual",budget:"Budget",prior:"Prior year",variance:"Budget var.",performanceTitle:"Monthly performance and closing forecast",forecastQuality:"FORECAST ACCURACY",quality:"Forecast quality",qualityDelta:"+2.8 p.p. in 3 months",forecastRows:["FY revenue","FY EBITDA","Closing cash"],drivers:"DRIVERS",assumptions:"Critical assumptions",assumptionRows:["Volume","Average price","Average FX rate","Inflation"],months:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"]},
es:{integrated:"ESTADOS INTEGRADOS",income:"Estado de resultados",incomeRows:["Ingresos netos","Costes directos","Margen bruto","OPEX","EBITDA","Resultado neto"],balance:"BALANCE",position:"Posición financiera",balanceRows:["Activos","Pasivos","Patrimonio neto","Deuda neta"],cashflow:"FLUJO DE CAJA",cashReconciliation:"Conciliación de caja",cashRows:["Operativo","Inversión","Financiación","Variación neta"],line:"Línea",actual:"Real",budget:"Presupuesto",prior:"Año anterior",variance:"Var. presupuesto",performanceTitle:"Rendimiento mensual y previsión de cierre",forecastQuality:"PRECISIÓN DE LA PREVISIÓN",quality:"Calidad de la previsión",qualityDelta:"+2,8 p.p. en 3 meses",forecastRows:["Ingresos anuales","EBITDA anual","Caja final"],drivers:"IMPULSORES",assumptions:"Supuestos críticos",assumptionRows:["Volumen","Precio medio","Cambio medio","Inflación"],months:["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago"]},
fr:{integrated:"ÉTATS INTÉGRÉS",income:"Compte de résultat",incomeRows:["Chiffre d’affaires net","Coûts directs","Marge brute","OPEX","EBITDA","Résultat net"],balance:"BILAN",position:"Situation financière",balanceRows:["Actifs","Passifs","Capitaux propres","Dette nette"],cashflow:"FLUX DE TRÉSORERIE",cashReconciliation:"Rapprochement de trésorerie",cashRows:["Exploitation","Investissement","Financement","Variation nette"],line:"Ligne",actual:"Réel",budget:"Budget",prior:"Année précédente",variance:"Écart budget",performanceTitle:"Performance mensuelle et prévision de clôture",forecastQuality:"PRÉCISION DES PRÉVISIONS",quality:"Qualité des prévisions",qualityDelta:"+2,8 p.p. en 3 mois",forecastRows:["CA annuel","EBITDA annuel","Trésorerie finale"],drivers:"INDUCTEURS",assumptions:"Hypothèses critiques",assumptionRows:["Volume","Prix moyen","Change moyen","Inflation"],months:["Jan","Fév","Mar","Avr","Mai","Juin","Juil","Aoû"]},
ru:{integrated:"ИНТЕГРИРОВАННАЯ ОТЧЁТНОСТЬ",income:"Отчёт о прибылях и убытках",incomeRows:["Чистая выручка","Прямые затраты","Валовая прибыль","OPEX","EBITDA","Чистая прибыль"],balance:"БАЛАНС",position:"Финансовое положение",balanceRows:["Активы","Обязательства","Капитал","Чистый долг"],cashflow:"ДЕНЕЖНЫЙ ПОТОК",cashReconciliation:"Сверка денежных средств",cashRows:["Операционная деятельность","Инвестиционная деятельность","Финансовая деятельность","Чистое изменение"],line:"Статья",actual:"Факт",budget:"Бюджет",prior:"Прошлый год",variance:"Откл. от бюджета",performanceTitle:"Месячные показатели и прогноз закрытия",forecastQuality:"ТОЧНОСТЬ ПРОГНОЗА",quality:"Качество прогноза",qualityDelta:"+2,8 п.п. за 3 месяца",forecastRows:["Годовая выручка","Годовая EBITDA","Денежные средства на конец"],drivers:"ДРАЙВЕРЫ",assumptions:"Критические допущения",assumptionRows:["Объём","Средняя цена","Средний валютный курс","Инфляция"],months:["Янв","Фев","Мар","Апр","Май","Июн","Июл","Авг"]}};

const packages = ["Cockpit CFO","Demonstrações","Performance","Desvios","Tesouraria","Working Capital","Rentabilidade","Management Pack"] as const;
type View=(typeof packages)[number];
const months=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago"];
const actual=[318,334,351,362,389,407,421,438], budget=[310,326,343,365,380,398,415,432], forecast=[318,334,351,362,389,407,426,449];
const money=(n:number)=>`${new Intl.NumberFormat("pt-PT",{maximumFractionDigits:1}).format(n)} M AOA`;
const pct=(n:number)=>`${n>0?"+":""}${n.toFixed(1)}%`;

export function FinanceSuite({initialView="Cockpit CFO"}:{initialView?:View}){
 const locale=usePlatformLocale(),c=fc[locale],d=fd[locale];
 const [view,setView]=useState<View>(initialView),[period,setPeriod]=useState("Agosto 2026"),[scenario,setScenario]=useState("Actual vs Budget"),[entity,setEntity]=useState("Grupo consolidado"),[detail,setDetail]=useState("");
 const variance=actual[7]-budget[7], variancePct=variance/budget[7]*100;
 const exportPack=()=>{const content=`MANAGEMENT PACK | ${entity} | ${period}\nReceita: ${money(438)}\nEBITDA: ${money(82.4)}\nResultado líquido: ${money(49.6)}\nCaixa: ${money(214.8)}\nDesvio receita: ${money(variance)} (${pct(variancePct)})\n\nConclusão: crescimento acima do orçamento, com pressão de margem logística e risco de concentração de clientes.`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/plain;charset=utf-8"}));a.download=`management-pack-${period.toLowerCase().replaceAll(" ","-")}.txt`;a.click();URL.revokeObjectURL(a.href)};
 return <section className="finance-suite">
  <header className="finance-hero"><div><span>FINANCE PERFORMANCE & DECISION MANAGEMENT</span><h1>{c.title}</h1><p>{c.intro}</p></div><div className="finance-controls"><label>{c.company}<select value={entity} onChange={e=>setEntity(e.target.value)}><option>{c.group}</option><option>{c.angola}</option><option>{c.corporate}</option></select></label><label>{c.period}<select value={period} onChange={e=>setPeriod(e.target.value)}><option>{c.aug}</option><option>{c.jul}</option><option>{c.quarter}</option></select></label><label>{c.comparison}<select value={scenario} onChange={e=>setScenario(e.target.value)}><option>Actual vs Budget</option><option>Actual vs Forecast</option><option>{c.previous}</option></select></label><button onClick={exportPack}>{c.export}</button></div></header>
  <nav className="finance-tabs" aria-label={c.tabs}>{packages.map((x,i)=><button key={x} className={view===x?"active":""} onClick={()=>{setView(x);setDetail("")}}><i>{i+1}</i>{x==="Demonstrações"?c.statements:x==="Performance"?c.performance:x==="Desvios"?c.variance:x==="Tesouraria"?c.treasury:x==="Rentabilidade"?c.profitability:x}</button>)}</nav>
  {view==="Cockpit CFO"&&<Cockpit onOpen={setView} onDetail={setDetail} c={c}/>} 
  {view==="Demonstrações"&&<Statements d={d}/>} 
  {view==="Performance"&&<Performance d={d}/>} 
  {view==="Desvios"&&<Bridges/>}
  {view==="Tesouraria"&&<Treasury/>}
  {view==="Working Capital"&&<WorkingCapital/>}
  {view==="Rentabilidade"&&<Profitability/>}
  {view==="Management Pack"&&<ManagementPack onExport={exportPack}/>} 
  {detail&&<div className="finance-drawer"><button onClick={()=>setDetail("")}>×</button><small>{c.drawer}</small><h2>{detail}</h2><p>{c.reconciled}</p><table><tbody><tr><th>{c.angola}</th><td>{money(288.4)}</td><td>65,8%</td></tr><tr><th>{c.corporate}</th><td>{money(91.7)}</td><td>20,9%</td></tr><tr><th>{c.other}</th><td>{money(57.9)}</td><td>13,3%</td></tr></tbody></table><footer>{c.source}</footer></div>}
 </section>
}

function Cockpit({onOpen,onDetail,c}:{onOpen:(x:View)=>void;onDetail:(x:string)=>void;c:Record<string,string>}){const kpis=[[c.revenue,438,"+1,4%",c.above],[c.ebitda,82.4,"−3,2%",c.pressure],[c.net,49.6,"+6,8%",c.interest],[c.cash,214.8,"+18,5%",c.runway]] as const;return <><section className="finance-kpis">{kpis.map((x,i)=><article key={x[0]} onClick={()=>onDetail(x[0])}><span>{x[0]}</span><strong>{money(x[1])}</strong><em className={i===1?"bad":"good"}>{x[2]}</em><small>{x[3]} · {c.detail}</small></article>)}</section><div className="finance-grid"><article className="finance-card span2"><CardTitle tag={c.trend} title={c.trendTitle} action={c.openPerformance} onClick={()=>onOpen("Performance")}/><TrendChart/></article><article className="finance-card"><CardTitle tag={c.liquidity} title={c.cashForecast} action={c.openTreasury} onClick={()=>onOpen("Tesouraria")}/><div className="cash-ring"><strong>214,8</strong><span>{c.available}</span></div><dl><div><dt>{c.minimum}</dt><dd>126,4 M</dd></div><div><dt>{c.buffer}</dt><dd>2,1×</dd></div></dl></article><article className="finance-card"><CardTitle tag={c.explanation} title={c.ebitdaMove} action={c.bridge} onClick={()=>onOpen("Desvios")}/><ul className="driver-list"><li><b>{c.priceMix}</b><em className="good">+12,6 M</em></li><li><b>{c.volume}</b><em className="good">+7,4 M</em></li><li><b>{c.logistics}</b><em className="bad">−14,8 M</em></li><li><b>{c.fx}</b><em className="bad">−8,1 M</em></li></ul></article><article className="finance-card span2"><CardTitle tag={c.action} title={c.priorities} action={c.pack} onClick={()=>onOpen("Management Pack")}/><div className="action-list"><span><i className="high">{c.high}</i><b>{c.renegotiate}</b><em>{c.ownerTreasury}</em></span><span><i>{c.medium}</i><b>{c.reviewTransport}</b><em>{c.ownerOps}</em></span><span><i>{c.monitor}</i><b>{c.covenant}</b><em>{c.margin}</em></span></div></article></div></>}
function CardTitle({tag,title,action,onClick}:{tag:string;title:string;action?:string;onClick?:()=>void}){return <header className="card-title"><div><span>{tag}</span><h2>{title}</h2></div>{action&&<button onClick={onClick}>{action} →</button>}</header>}
function TrendChart({d=fd.pt}:{d?:DeepCopy}){const max=470;return <div className="trend-chart"><div className="chart-legend"><span><i className="a"/>{d.actual}</span><span><i className="b"/>{d.budget}</span><span><i className="f"/>Forecast</span></div><div className="bars">{d.months.map((m,i)=><div key={m}><section><i className="b" style={{height:`${budget[i]/max*100}%`}}/><i className="a" style={{height:`${actual[i]/max*100}%`}}/><i className="f" style={{height:`${forecast[i]/max*100}%`}}/></section><small>{m}</small></div>)}</div></div>}
function Statements({d}:{d:DeepCopy}){const rows=d.incomeRows.map((x,i)=>[x,...[[438,432,406],[-246,-231,-224],[192,201,182],[-109.6,-116,-108],[82.4,85,74],[49.6,46.4,41.2]][i]]);return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag={d.integrated} title={d.income}/><FinanceTable rows={rows} d={d}/></article><article className="finance-card"><CardTitle tag={d.balance} title={d.position}/><MetricRows rows={d.balanceRows.map((x,i)=>[x,[1284,716,568,301][i]])}/></article><article className="finance-card"><CardTitle tag={d.cashflow} title={d.cashReconciliation}/><MetricRows rows={d.cashRows.map((x,i)=>[x,[96.8,-42.1,18.4,73.1][i]])}/></article></div>}
function FinanceTable({rows,d}:{rows:(string|number)[][];d:DeepCopy}){return <div className="finance-table"><table><thead><tr><th>{d.line}</th><th>{d.actual}</th><th>{d.budget}</th><th>{d.prior}</th><th>{d.variance}</th></tr></thead><tbody>{rows.map(r=><tr key={String(r[0])}><th>{r[0]}</th><td>{money(Number(r[1]))}</td><td>{money(Number(r[2]))}</td><td>{money(Number(r[3]))}</td><td className={Number(r[1])-Number(r[2])>=0?"good":"bad"}>{money(Number(r[1])-Number(r[2]))}</td></tr>)}</tbody></table></div>}
function MetricRows({rows}:{rows:[string,number][]}){return <div className="metric-rows">{rows.map(x=><div key={x[0]}><span>{x[0]}</span><b>{money(x[1])}</b></div>)}</div>}
function Performance({d}:{d:DeepCopy}){return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="ACTUAL · BUDGET · FORECAST" title={d.performanceTitle}/><TrendChart d={d}/></article><article className="finance-card"><CardTitle tag={d.forecastQuality} title={d.quality}/><div className="score"><strong>94,2%</strong><span>{d.qualityDelta}</span></div><MetricRows rows={d.forecastRows.map((x,i)=>[x,[5284,988,236][i]])}/></article><article className="finance-card"><CardTitle tag={d.drivers} title={d.assumptions}/><ul className="driver-list">{d.assumptionRows.map((x,i)=><li key={x}><b>{x}</b><em>{["+4,2%","+2,6%","1 012 AOA","18,4%"][i]}</em></li>)}</ul></article></div>}
function Bridges(){const items:[[string,number,string],...Array<[string,number,string]>]=[["EBITDA Budget",85,"base"],["Preço",9.8,"up"],["Volume",5.7,"up"],["Mix",-2.9,"down"],["Logística",-8.6,"down"],["Câmbio",-6.6,"down"],["EBITDA Actual",82.4,"total"]];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="VARIANCE BRIDGE" title="Da expectativa ao resultado"/><div className="bridge">{items.map(x=><div key={x[0]}><span>{x[0]}</span><i className={x[2]} style={{height:`${Math.max(22,Math.abs(x[1])*2.1)}px`}}/><b>{x[1]>0?"+":""}{x[1]} M</b></div>)}</div></article><article className="finance-card"><CardTitle tag="CAUSAS" title="Classificação do desvio"/><MetricRows rows={[["Controlável",-9.1],["Não controlável",-4.6],["Recorrente",-5.8],["Não recorrente",-7.9]]}/></article><article className="finance-card"><CardTitle tag="IMPACTO" title="Perspetiva anual"/><div className="score warning"><strong>−38,6 M</strong><span>Risco EBITDA se nenhuma ação for executada</span></div></article></div>}
function Treasury(){const weeks=[214,202,187,192,174,158,146,132,126,139,151,168,183];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="13-WEEK CASH FORECAST" title="Liquidez projetada"/><div className="line-bars">{weeks.map((x,i)=><div key={i}><i style={{height:`${x/2.4}px`}}/><b>{x}</b><small>S{i+1}</small></div>)}</div></article><article className="finance-card"><CardTitle tag="POSIÇÃO BANCÁRIA" title="Caixa por moeda"/><MetricRows rows={[["AOA",124.6],["USD",76.2],["EUR",14.0]]}/></article><article className="finance-card"><CardTitle tag="DÍVIDA" title="Financiamento e covenants"/><MetricRows rows={[["Dívida bruta",515.8],["Dívida líquida",301],["Serviço 90 dias",72.5]]}/><p className="status-note good">✓ Covenants dentro do limite · DSCR 1,42×</p></article></div>}
function WorkingCapital(){return <div className="finance-grid"><article className="finance-card"><CardTitle tag="CICLO DE CAIXA" title="Cash Conversion Cycle"/><div className="score"><strong>48 dias</strong><span>−6 dias vs trimestre anterior</span></div><MetricRows rows={[["DSO · 62 dias",286],["DIO · 31 dias",144],["DPO · 45 dias",209]]}/></article><article className="finance-card span2"><CardTitle tag="AGING" title="Contas a receber"/><div className="aging">{[["Não vencido",184,64],["1–30 dias",58,20],["31–60 dias",27,9],["61–90 dias",12,4],["> 90 dias",8,3]].map(x=><div key={x[0]}><span>{x[0]}</span><section><i style={{width:`${x[2]}%`}}/></section><b>{money(x[1])}</b></div>)}</div></article><article className="finance-card span2"><CardTitle tag="OPORTUNIDADE" title="Libertação potencial de caixa"/><div className="opportunity"><strong>28,4 M AOA</strong><p>Reduzindo o DSO de 62 para 55 dias através de cobrança priorizada nos 10 maiores saldos.</p><button>Converter em plano de ação →</button></div></article></div>}
function Profitability(){const rows=[["Serviços Enterprise",188,34.8,28.1],["Operações",142,21.4,17.9],["Projetos",71,18.6,12.8],["Suporte",37,9.2,6.1]];return <div className="finance-grid"><article className="finance-card span2"><CardTitle tag="RENTABILIDADE MULTIDIMENSIONAL" title="Margem por unidade de negócio"/><div className="finance-table"><table><thead><tr><th>Unidade</th><th>Receita</th><th>Margem bruta</th><th>Margem contribuição</th><th>Sinal</th></tr></thead><tbody>{rows.map(x=><tr key={String(x[0])}><th>{x[0]}</th><td>{money(Number(x[1]))}</td><td>{x[2]}%</td><td>{x[3]}%</td><td><em className={Number(x[3])>10?"good":"bad"}>{Number(x[3])>10?"Criador de valor":"Rever"}</em></td></tr>)}</tbody></table></div></article><article className="finance-card"><CardTitle tag="UNIT ECONOMICS" title="Economia por cliente"/><MetricRows rows={[["Receita média",12.8],["Cost-to-serve",8.1],["Contribuição",4.7]]}/></article><article className="finance-card"><CardTitle tag="CONCENTRAÇÃO" title="Risco comercial"/><div className="score warning"><strong>38%</strong><span>da receita nos 3 maiores clientes</span></div><p className="status-note bad">! Acima do limite interno de 35%</p></article></div>}
function ManagementPack({onExport}:{onExport:()=>void}){return <div className="pack"><header><div><small>BOARD & MANAGEMENT REPORTING</small><h2>Management Pack · Agosto 2026</h2><p>Grupo consolidado · Actual vs Budget · Versão aprovada</p></div><button onClick={onExport}>Download do relatório ↓</button></header><section><article><span>01 · RESULTADO</span><h3>Crescimento acima do plano, com pressão operacional sobre a margem</h3><p>A receita atingiu 438 M AOA, 1,4% acima do orçamento. O EBITDA ficou 3,2% abaixo devido a custos logísticos e impacto cambial.</p></article><article><span>02 · COMPARAÇÃO E CAUSA</span><h3>Preço e volume compensaram parcialmente custos externos</h3><p>Preço, mix e volume contribuíram positivamente com 12,6 M AOA; logística e câmbio retiraram 14,8 M AOA.</p></article><article><span>03 · IMPACTO E PERSPETIVA</span><h3>Liquidez protegida, mas o risco anual exige resposta</h3><p>O caixa mínimo projetado é 126,4 M AOA. Sem ações, o risco anual sobre EBITDA pode alcançar 38,6 M AOA.</p></article><article><span>04 · RECOMENDAÇÃO</span><h3>Atuar sobre cobrança, logística e exposição cambial</h3><ol><li>Reduzir DSO para 55 dias.</li><li>Renegociar contrato logístico.</li><li>Proteger 60% da exposição cambial prevista.</li></ol></article></section><footer><b>Governação:</b> valores determinísticos · evidência preservada · narrativa sujeita a aprovação do CFO</footer></div>}
