"use client";
import { useState } from "react";
import "./hr-manager-suite.css";

const monthly=[132,135,137,139,141,143,146,148];
const money=(n:number)=>`${n.toFixed(1)} M AOA`;
export function HrManagerSuite({onNavigate}:{onNavigate:(x:string)=>void}){
 const [view,setView]=useState<"overview"|"people"|"cost"|"talent">("overview"),[period,setPeriod]=useState("Agosto 2026"),[unit,setUnit]=useState("Toda a empresa");
 return <section className="hr-suite"><header className="hr-head"><div><span>RH · PEOPLE & PAYROLL MANAGEMENT</span><h1>Centro de gestão de pessoas</h1><p>Da contratação ao pagamento, desempenho e desenvolvimento — com pessoas, custos e decisões no mesmo contexto.</p></div><div><label>Âmbito<select value={unit} onChange={e=>setUnit(e.target.value)}><option>Toda a empresa</option><option>Operações</option><option>Serviços Corporativos</option></select></label><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}><option>Agosto 2026</option><option>Julho 2026</option><option>2.º Trimestre 2026</option></select></label></div></header>
 <nav className="hr-tabs"><button className={view==="overview"?"active":""} onClick={()=>setView("overview")}>Visão do Gestor RH</button><button className={view==="people"?"active":""} onClick={()=>setView("people")}>Pessoas & Operações</button><button className={view==="cost"?"active":""} onClick={()=>setView("cost")}>Payroll & Custos</button><button className={view==="talent"?"active":""} onClick={()=>setView("talent")}>Talento & Performance</button></nav>
 {view==="overview"&&<><section className="hr-kpis">{[["Colaboradores ativos","148","+4 vs plano","good"],["Custo total de pessoas","95,5 M AOA","21,8% da receita","neutral"],["Turnover acumulado","7,8%","−1,2 p.p.","good"],["Absentismo","3,4%","+0,6 p.p.","bad"],["Vagas abertas","9","4 críticas","bad"],["Performance média","82%","+4 p.p.","good"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><em className={x[3]}>{x[2]}</em></article>)}</section><div className="hr-grid"><article className="hr-card span2"><Title tag="WORKFORCE" title="Evolução do headcount"/><div className="headcount-chart">{monthly.map((x,i)=><div key={i}><b>{x}</b><i style={{height:`${(x-115)*4}px`}}/><small>{["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago"][i]}</small></div>)}</div><footer className="hr-legend"><span><i/>Actual 148</span><span><i/>Plano 152</span><em>Gap: −4 posições</em></footer></article><article className="hr-card"><Title tag="ESTRUTURA" title="Pessoas por área"/><div className="people-mix">{[["Operações",72,49],["Comercial",28,19],["Finance & Admin",24,16],["Tecnologia",15,10],["Direção",9,6]].map(x=><div key={x[0]}><span>{x[0]}</span><section><i style={{width:`${x[2]}%`}}/></section><b>{x[1]}</b></div>)}</div></article><article className="hr-card"><Title tag="ATENÇÃO" title="Riscos de pessoas"/><div className="people-risks"><span><i className="high">4</i><b>Vagas críticas</b><small>Prazo médio: 38 dias</small></span><span><i className="mid">7</i><b>Talentos em risco</b><small>Retenção recomendada</small></span><span><i className="mid">12</i><b>Documentos a expirar</b><small>Próximos 30 dias</small></span><span><i>3</i><b>Avaliações pendentes</b><small>Prazo: 5 dias</small></span></div></article><article className="hr-card span2"><Title tag="AGENDA DO GESTOR" title="Decisões e prioridades"/><div className="hr-agenda">{[["Alta","Aprovar Payroll e payment batch","Payroll","Hoje"],["Alta","Decidir 4 candidatos para posições críticas","Recrutamento","2 dias"],["Média","Validar plano de férias do trimestre","Ausências","5 dias"],["Média","Concluir calibração de performance","Performance","7 dias"]].map(x=><span key={x[1]}><i className={x[0]==="Alta"?"high":""}>{x[0]}</i><b>{x[1]}</b><small>{x[2]}</small><em>{x[3]}</em></span>)}</div></article></div></>}
 {view==="people"&&<div className="hr-grid"><article className="hr-card span2"><Title tag="CICLO DO COLABORADOR" title="Do recrutamento à saída"/><div className="employee-flow">{[["Candidatos",42,"Recrutamento"],["Admissões",6,"Pessoas"],["Ativos",148,"Pessoas"],["Em experiência",11,"Pessoas"],["Saídas previstas",3,"Pessoas"]].map((x,i)=><button key={x[0]} onClick={()=>onNavigate(String(x[2]))}><i>{i+1}</i><b>{x[1]}</b><span>{x[0]}</span><small>Abrir →</small></button>)}</div></article><article className="hr-card"><Title tag="ASSIDUIDADE" title="Presença e tempo"/><div className="hr-score"><strong>96,6%</strong><span>Taxa de presença</span></div><Metric rows={[["Timesheets aprovados","139/148"],["Horas extra","284 h"],["Atrasos","21"],["Exceções","6"]]}/><button className="hr-open" onClick={()=>onNavigate("Assiduidade")}>Abrir assiduidade →</button></article><article className="hr-card"><Title tag="AUSÊNCIAS" title="Saldos e planeamento"/><Metric rows={[["Em férias","8"],["Pedidos pendentes","5"],["Baixas médicas","3"],["Saldo médio","14,2 dias"]]}/><button className="hr-open" onClick={()=>onNavigate("Ausências")}>Gerir ausências →</button></article><article className="hr-card span2"><Title tag="DOCUMENTAÇÃO" title="Conformidade do Employee Master"/><div className="compliance"><strong>94%</strong><section><i style={{width:"94%"}}/></section><span>139 fichas completas · 9 com pendências documentais</span><button onClick={()=>onNavigate("Documentos HCM")}>Rever documentos →</button></div></article></div>}
 {view==="cost"&&<div className="hr-grid"><article className="hr-card span2"><Title tag="PAYROLL" title="Custo mensal de pessoas"/><div className="payroll-stack">{[["Salário base",68.4,72],["Subsídios",11.2,12],["Horas extra",3.7,4],["Encargos empregador",9.1,9.5],["Outros",3.1,2.5]].map(x=><div key={x[0]}><span>{x[0]}</span><section><i style={{width:`${x[2]}%`}}/></section><b>{money(Number(x[1]))}</b></div>)}</div></article><article className="hr-card"><Title tag="PROCESSAMENTO" title="Payroll de Agosto"/><div className="payroll-status"><i>92%</i><b>Em validação</b><span>146 de 148 colaboradores reconciliados</span></div><Metric rows={[["Bruto","86,4 M"],["Líquido","74,8 M"],["Encargos","9,1 M"],["Payment batch","83,9 M"]]}/><button className="hr-open" onClick={()=>onNavigate("Operações")}>Abrir Payroll →</button></article><article className="hr-card"><Title tag="WORKFORCE COST" title="Actual vs Budget"/><div className="cost-variance"><strong>+2,8%</strong><span>2,6 M AOA desfavorável</span></div><Metric rows={[["Actual","95,5 M"],["Budget","92,9 M"],["Forecast","96,2 M"],["Custo/receita","21,8%"]]}/><button className="hr-open" onClick={()=>onNavigate("Análises")}>Analisar custos →</button></article><article className="hr-card span2"><Title tag="EXPLICAÇÃO" title="O que alterou o custo de pessoas"/><div className="cost-drivers">{[["Novas admissões",3.8,"up"],["Horas extra",1.4,"up"],["Saídas",-1.2,"down"],["Ausências",-0.5,"down"],["Ajustes",-0.9,"down"]].map(x=><span key={x[0]}><b>{x[0]}</b><i className={x[2]} style={{height:`${Math.abs(Number(x[1]))*18+18}px`}}/><em>{Number(x[1])>0?"+":""}{x[1]} M</em></span>)}</div></article></div>}
 {view==="talent"&&<div className="hr-grid"><article className="hr-card"><Title tag="PERFORMANCE" title="Distribuição de resultados"/><div className="talent-bars">{[["Excecional",12,8],["Acima",39,26],["No rumo",74,50],["A desenvolver",19,13],["Crítico",4,3]].map(x=><div key={x[0]}><span>{x[0]}</span><section><i style={{width:`${x[2]*1.7}%`}}/></section><b>{x[1]}</b></div>)}</div></article><article className="hr-card span2"><Title tag="TALENTO" title="Matriz performance × potencial"/><div className="nine-box">{[["Especialista sólido","Alto desempenho","Sucessor imediato"],["Contribuidor-chave","Talento em crescimento","Líder emergente"],["Apoiar evolução","Reorientar função","Intervenção crítica"]].flat().map((x,i)=><span key={x} className={i===2||i===5?"star":i>=6?"risk":""}><b>{x}</b><small>{[12,18,7,24,31,9,19,17,4][i]} pessoas</small></span>)}</div></article><article className="hr-card"><Title tag="DESENVOLVIMENTO" title="Planos e competências"/><Metric rows={[["Planos ativos","46"],["Competências avaliadas","82%"],["Sucessores prontos","7"],["Formação concluída","74%"]]}/><button className="hr-open" onClick={()=>onNavigate("Competências")}>Abrir competências →</button></article><article className="hr-card span2"><Title tag="RECOMENDAÇÕES" title="Ações do Gestor de RH"/><div className="talent-actions"><span><b>Retenção</b><p>Preparar proposta para 7 talentos com risco elevado e funções críticas.</p><button>Iniciar plano →</button></span><span><b>Sucessão</b><p>Validar 3 posições sem sucessor identificado no comité de talento.</p><button>Rever posições →</button></span><span><b>Desenvolvimento</b><p>Criar trilha de liderança para 9 colaboradores de alto potencial.</p><button>Plano de desenvolvimento →</button></span></div></article></div>}
 </section>
}
function Title({tag,title}:{tag:string;title:string}){return <header className="hr-title"><span>{tag}</span><h2>{title}</h2></header>}
function Metric({rows}:{rows:string[][]}){return <div className="hr-metric">{rows.map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>}
