"use client";
import{FormEvent,useCallback,useEffect,useState}from"react";
import{apiFetch}from"../lib/api-client";
import"./integrations.css";
type Source={id:string;code:string;name:string;connector_type:string;direction:string;status:string;run_count:number};
type Run={id:string;source_name:string;source_code:string;organization_name:string;run_number:number;status:string;record_count:number;accepted_count:number;rejected_count:number;input_hash:string;created_by:string;validated_by?:string};
type Data={sources:Source[];runs:Run[];mappings:Array<{source_system:string;mapping_count:number}>;organizations:Array<{id:string;code:string;name:string}>};
const empty:Data={sources:[],runs:[],mappings:[],organizations:[]};
export function IntegrationsWorkspace(){const[data,setData]=useState<Data>(empty),[view,setView]=useState("Execuções"),[modal,setModal]=useState(""),[target,setTarget]=useState<Run|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(()=>apiFetch("/api/v1/integrations").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);
 async function command(payload:Record<string,string>){setBusy(true);setError("");const r=await apiFetch("/api/v1/integrations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();setBusy(false);if(!r.ok){setError(b.error);return}setData(b);setModal("");setTarget(null)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget).entries())as Record<string,string>;await command({type:modal,runId:target?.id||"",...fields})}
 const pending=data.runs.filter(x=>x.status==="Recebida"||x.status==="Validada").length,accepted=data.runs.reduce((n,x)=>n+x.accepted_count,0),rejected=data.runs.reduce((n,x)=>n+x.rejected_count,0);
 return <section className="integration-hub"><header className="ih-top"><div><span>INTEGRATION HUB · GOVERNED DATA EXCHANGE</span><h1>Dados conectados, validação antes da verdade</h1><p>Fontes agnósticas, execuções idempotentes, reconciliação de contagens e aprovação maker-checker.</p></div><div><button className="secundario" onClick={()=>setModal("createSource")}>＋ Fonte</button><button className="primario" disabled={!data.sources.length||!data.organizations.length} onClick={()=>setModal("receiveRun")}>▶ Nova execução</button></div></header>
 <section className="ih-kpis"><article><span>Fontes ativas</span><strong>{data.sources.filter(x=>x.status==="Ativa").length}</strong><small>Conectores configurados</small></article><article><span>Mappings financeiros</span><strong>{data.mappings.reduce((n,x)=>n+x.mapping_count,0)}</strong><small>{data.mappings.length} sistema(s) de origem</small></article><article><span>Em decisão</span><strong>{pending}</strong><small>Recebidas ou validadas</small></article><article className={rejected?"risk":""}><span>Registos reconciliados</span><strong>{accepted+rejected}</strong><small>{rejected} rejeitado(s)</small></article></section>
 <nav className="ih-tabs">{["Execuções","Fontes","Mappings"].map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}>{x}</button>)}</nav>
 {view==="Execuções"?<article className="cartao ih-table"><div className="cab"><div><span>EXECUTION LOG</span><h2>Histórico imutável de integrações</h2></div><em>{data.runs.length} execução(ões)</em></div><div className="table-scroll"><table><thead><tr><th>Execução</th><th>Fonte</th><th>Organização</th><th>Contagens</th><th>Estado</th><th>Ação</th></tr></thead><tbody>{data.runs.map(x=><tr key={x.id}><td><b>#{x.run_number}</b><small>{x.input_hash.slice(0,12)}…</small></td><td><b>{x.source_name}</b><small>{x.source_code}</small></td><td>{x.organization_name}</td><td>{x.record_count} · {x.accepted_count} aceites · {x.rejected_count} rejeitados</td><td><em className={`ih-status ${x.status.toLowerCase()}`}>{x.status}</em></td><td>{x.status==="Recebida"?<button onClick={()=>{setTarget(x);setModal("validateRun")}}>Validar</button>:x.status==="Validada"?<button onClick={()=>{setTarget(x);setModal("decideRun")}}>Decidir</button>:"—"}</td></tr>)}</tbody></table></div></article>:view==="Fontes"?<section className="ih-sources">{data.sources.map(x=><article className="cartao" key={x.id}><i>{x.code.slice(0,2)}</i><span><b>{x.name}</b><small>{x.connector_type} · {x.direction}</small></span><em>{x.status}</em><strong>{x.run_count}<small>execuções</small></strong></article>)}</section>:<article className="cartao ih-table"><div className="cab"><div><span>MAPPING COVERAGE</span><h2>Traduções financeiras reutilizadas</h2></div><button onClick={()=>location.assign("/")}>Abrir dados financeiros →</button></div><table><thead><tr><th>Sistema de origem</th><th>Mappings governados</th><th>Motor consumidor</th></tr></thead><tbody>{data.mappings.map(x=><tr key={x.source_system}><td><b>{x.source_system}</b></td><td>{x.mapping_count}</td><td>Finance &amp; FP&amp;A</td></tr>)}</tbody></table></article>}
 {error&&<p className="erro-global">{error}</p>}{modal&&<div className="modal-inline"><form onSubmit={submit}><header><div><small>INTEGRATION HUB</small><h2>{modal==="createSource"?"Configurar fonte":modal==="receiveRun"?"Receber execução":modal==="validateRun"?"Reconciliar contagens":"Decidir execução"}</h2></div><button type="button" onClick={()=>{setModal("");setTarget(null)}}>×</button></header>{modal==="createSource"?<><div><label>Código<input name="code" required/></label><label>Conector<select name="connectorType"><option>API</option><option>SFTP</option><option>Ficheiro</option><option>Base de dados</option></select></label></div><label>Nome<input name="name" required/></label><label>Direção<select name="direction"><option>Entrada</option><option>Saída</option><option>Bidirecional</option></select></label></>:modal==="receiveRun"?<><label>Fonte<select name="sourceId" required>{data.sources.filter(x=>x.status==="Ativa").map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Organização<select name="organizationId" required>{data.organizations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><div><label>Chave idempotente<input name="idempotencyKey" required/></label><label>N.º de registos<input name="recordCount" type="number" min="0" required/></label></div></>:modal==="validateRun"?<><p>A soma de aceites e rejeitados deve reconciliar exatamente os {target?.record_count} registos recebidos.</p><div><label>Aceites<input name="acceptedCount" type="number" min="0" required/></label><label>Rejeitados<input name="rejectedCount" type="number" min="0" required/></label></div></>:<><label>Decisão<select name="decision"><option>Aprovada</option><option>Rejeitada</option></select></label><label>Nota de decisão<textarea name="note" required/></label></>}<footer><button type="button" className="secundario" onClick={()=>setModal("")}>Cancelar</button><button className="primario" disabled={busy}>Confirmar</button></footer></form></div>}
 </section>}
