"use client";
import{useCallback,useEffect,useState}from"react";
import{apiFetch}from"../lib/api-client";
import"./notifications.css";
import"./notification-tasks.css";
type Alert={id:string;domain:string;title:string;detail:string;dueAt:string;target:string;severity:string;canAct:boolean;taskId?:string;taskStatus?:string};
type Data={generatedAt:string;items:Alert[];summary:{total:number;actionable:number;critical:number;claimed:number}};
export function NotificationsCenter({open,onClose,onNavigate,onCount}:{open:boolean;onClose:()=>void;onNavigate:(target:string)=>void;onCount:(count:number)=>void}){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(()=>apiFetch("/api/v1/notifications").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);onCount(b.summary.total)}).catch(e=>setError(e.message)),[onCount]);
 useEffect(()=>{load()},[open,load]);
 async function command(payload:Record<string,string>){setBusy(payload.taskId||`${payload.domain}-${payload.sourceId}`);setError("");const r=await apiFetch("/api/v1/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();setBusy("");if(!r.ok){setError(b.error||"Não foi possível atualizar a tarefa.");return}load()}
 function claim(x:Alert){return command({type:"claim",sourceId:x.id,domain:x.domain,title:x.title,detail:x.detail,target:x.target,dueAt:x.dueAt,severity:x.severity})}
 function complete(x:Alert){const evidence=window.prompt("Indique a evidência objetiva da conclusão:")||"";if(evidence.trim().length<3)return;return command({type:"transition",taskId:String(x.taskId),status:"Concluída",evidence})}
 if(!open)return null;
 return <><button className="notification-backdrop" aria-label="Fechar alertas" onClick={onClose}/><aside className="notification-panel"><header><div><small>CENTRO DE ALERTAS</small><h2>O que exige atenção</h2></div><button onClick={onClose}>×</button></header>{data&&<section className="notification-summary"><span><b>{data.summary.total}</b><small>Total</small></span><span><b>{data.summary.actionable}</b><small>Posso agir</small></span><span className={data.summary.critical?"critical":""}><b>{data.summary.critical}</b><small>Críticos</small></span><span><b>{data.summary.claimed||0}</b><small>Assumidos</small></span></section>}<div className="notification-list">{data?.items.length?data.items.map(x=><article key={`${x.domain}-${x.id}`}><i className={x.severity.toLowerCase()}>{x.severity==="Crítica"?"!":"◷"}</i><span><small>{x.domain} · {x.severity}</small><b>{x.title}</b><p>{x.detail}</p><em>Prazo {new Date(x.dueAt).toLocaleString("pt-AO")}</em>{x.taskStatus&&<mark>{x.taskStatus} · sob responsabilidade</mark>}</span><div className="notification-actions">{x.canAct&&!x.taskId&&<button disabled={busy===`${x.domain}-${x.id}`} onClick={()=>claim(x)}>{busy===`${x.domain}-${x.id}`?"A assumir…":"Assumir"}</button>}{x.canAct&&x.taskId&&<button disabled={busy===x.taskId} onClick={()=>complete(x)}>{busy===x.taskId?"A concluir…":"Concluir"}</button>}<button onClick={()=>{onNavigate(x.target);onClose()}}>{x.canAct?"Agir":"Abrir"} →</button></div></article>):<p className="notification-empty">Não existem alertas no seu âmbito.</p>}{error&&<p className="erro-global">{error}</p>}</div><footer><button onClick={()=>{onNavigate("Workflow");onClose()}}>Abrir Workflow completo →</button></footer></aside></>
}
