"use client";
import { useMemo, useState } from "react";

const colaboradores = [
  ["Ana Manuel","EMP-001","Serviços Corporativos","Gestora Financeira","Ativo"],
  ["Mateus Costa","EMP-002","Operações","Responsável de Operações","Ativo"],
  ["Elisa Rocha","EMP-003","Pessoas e Cultura","Parceira de RH","Pendente"],
  ["David Kim","EMP-004","Serviços Corporativos","Analista de FP&A","Ativo"],
];
const modulos = ["Visão geral","Planeamento","Operações","Análises","Relatórios","Administração"];

export default function Home(){
 const [modulo,setModulo]=useState("Visão geral"),[pesquisa,setPesquisa]=useState(""),[painel,setPainel]=useState(false);
 const lista=useMemo(()=>colaboradores.filter(x=>x.join(" ").toLowerCase().includes(pesquisa.toLowerCase())),[pesquisa]);
 return <div className="site">
  <header className="topo">
   <div className="marca"><b>EP</b><span>Enterprise Performance</span></div>
   <nav aria-label="Navegação principal">{modulos.map(x=><button key={x} className={modulo===x?"selecionado":""} onClick={()=>setModulo(x)}>{x}</button>)}</nav>
   <div className="acoes"><button className="pesquisa-global">⌕ <span>Pesquisar</span><kbd>⌘K</kbd></button><button className="notificacao">◌<i/></button><button className="perfil"><b>PF</b><span>Pascoal Frederico<small>Administrador</small></span>⌄</button></div>
  </header>
  <div className="subnav"><div className="empresa"><span>DH</span><p><small>Empresa atual</small><b>Demo Holdings⌄</b></p></div><div className="atalhos"><button className="ativo">Resumo</button><button>Desempenho</button><button>Pessoas</button><button>Atividades</button></div><button className="ajuda">? Ajuda</button></div>
  <main>
   {modulo==="Administração"?<Configuracao/>:<>
   <section className="boas-vindas"><div><span className="etiqueta">SEGUNDA-FEIRA, 17 DE AGOSTO</span><h1>Boa tarde, Pascoal.</h1><p>Aqui está o que precisa da sua atenção e como a organização está a evoluir.</p></div><div className="botoes"><button className="secundario">↥ Exportar visão</button><button className="primario" onClick={()=>setPainel(true)}>＋ Criar atividade</button></div></section>
   <section className="filtros"><div><label>Período<select><option>Agosto 2026</option><option>Julho 2026</option></select></label><label>Cenário<select><option>Realizado</option><option>Orçamento</option><option>Previsão</option></select></label><label>Versão<select><option>Versão de trabalho 3</option></select></label><label>Moeda<select><option>Moeda de reporte</option></select></label></div><span>Atualizado há 2 minutos</span></section>
   <section className="resumo"><article className="destaque"><div><span>Resultado operacional</span><i>↗ 6,8%</i></div><strong>8,42 M USD</strong><p>540 mil USD acima do orçamento</p><div className="spark"><i/><i/><i/><i/><i/><i/><i/><i/></div></article><Metrica titulo="Custo da força de trabalho" valor="3,18 M USD" nota="2,4% acima do orçamento" cor="ambar"/><Metrica titulo="Colaboradores ativos" valor="148" nota="96,2% das posições ocupadas" cor="azul"/><Metrica titulo="Ações pendentes" valor="4" nota="2 requerem decisão hoje" cor="vermelho"/></section>
   <section className="grelha">
    <article className="cartao desempenho"><Cabecalho sobre="DESEMPENHO" titulo="Realizado versus orçamento" acao="Abrir análise"/><div className="legenda"><span><i className="real"/>Realizado</span><span><i className="orc"/>Orçamento</span><b>Mar — Ago 2026</b></div><div className="grafico"><div className="escala"><span>12 M</span><span>9 M</span><span>6 M</span><span>3 M</span><span>0</span></div><div className="plot"><i/><i/><i/><i/><svg viewBox="0 0 800 220" preserveAspectRatio="none"><path className="area" d="M0,183 C80,165 110,155 170,158 S270,118 330,130 S430,82 500,92 S600,45 680,58 S750,28 800,25 L800,220 L0,220Z"/><path className="linha-real" d="M0,183 C80,165 110,155 170,158 S270,118 330,130 S430,82 500,92 S600,45 680,58 S750,28 800,25"/><path className="linha-orc" d="M0,177 C100,165 150,146 210,148 S330,122 400,112 S520,90 600,82 S700,60 800,53"/></svg><div className="meses">{["Mar","Abr","Mai","Jun","Jul","Ago"].map(x=><span key={x}>{x}</span>)}</div></div></div><div className="explicacao"><i>✦</i><div><b>O que explica a evolução?</b><p>O resultado superou o plano em julho, impulsionado pelas receitas de serviços e menor despesa externa.</p></div><button>Ver causas →</button></div></article>
    <article className="cartao foco"><Cabecalho sobre="FOCO DO DIA" titulo="Prioridades para decisão" acao="Ver todas"/><Prioridade cor="vermelho" icone="!" titulo="Bloqueios na validação salarial" texto="3 colaboradores com dados de pagamento incompletos." etiqueta="Resolver hoje"/><Prioridade cor="ambar" icone="↗" titulo="Desvio de custos em Operações" texto="Horas extraordinárias 18,6% acima do plano." etiqueta="Impacto elevado"/><Prioridade cor="azul" icone="◷" titulo="Orçamento por aprovar" texto="Dois centros de custo aguardam revisão." etiqueta="Há 2 dias"/><footer><span>Impacto potencial</span><b>214 mil USD</b><p>Exposição estimada caso nenhuma ação seja tomada.</p></footer></article>
   </section>
   <section className="cartao equipa"><div className="cab-equipa"><Cabecalho sobre="ORGANIZAÇÃO E PESSOAS" titulo="Acompanhar a equipa" acao="Abrir módulo de Pessoas"/><div><label>⌕<input value={pesquisa} onChange={e=>setPesquisa(e.target.value)} placeholder="Pesquisar colaborador"/></label><button className="primario" onClick={()=>setPainel(true)}>＋ Novo colaborador</button></div></div><div className="lista">{lista.map(x=><article key={x[1]}><i>{x[0].split(" ").map(y=>y[0]).join("").slice(0,2)}</i><div><b>{x[0]}</b><span>{x[3]}</span></div><p>{x[2]}<small>{x[1]}</small></p><em className={x[4]==="Ativo"?"ok":"pendente"}>{x[4]}</em><button>•••</button></article>)}</div><footer><span>A mostrar {lista.length} de {colaboradores.length} colaboradores</span><button>Ver diretório completo →</button></footer></section>
   </>}
  </main>
  {painel&&<div className="overlay" onClick={()=>setPainel(false)}><aside className="painel" onClick={e=>e.stopPropagation()}><header><div><small>PESSOAS</small><h2>Novo colaborador</h2></div><button onClick={()=>setPainel(false)}>×</button></header><div className="form"><p>Registe os dados essenciais. Contrato e processamento salarial serão tratados nos respetivos fluxos.</p><label>Número do colaborador<input placeholder="EMP-005"/></label><div><label>Nome<input/></label><label>Apelido<input/></label></div><label>Unidade organizacional<select><option>Serviços Corporativos</option><option>Operações</option></select></label><label>Data de admissão<input type="date"/></label><aside><b>✓ Auditoria ativa</b><p>O utilizador, a data, o contexto e os dados submetidos serão registados.</p></aside></div><footer><button className="secundario" onClick={()=>setPainel(false)}>Cancelar</button><button className="primario" onClick={()=>setPainel(false)}>Criar colaborador</button></footer></aside></div>}
 </div>
}
function Metrica({titulo,valor,nota,cor}:{titulo:string;valor:string;nota:string;cor:string}){return <article className="metrica"><span>{titulo}</span><strong>{valor}</strong><p className={cor}>{nota}</p><div><i className={cor}/></div></article>}
function Cabecalho({sobre,titulo,acao}:{sobre:string;titulo:string;acao:string}){return <div className="cab"><div><span>{sobre}</span><h2>{titulo}</h2></div><button>{acao} →</button></div>}
function Prioridade({cor,icone,titulo,texto,etiqueta}:{cor:string;icone:string;titulo:string;texto:string;etiqueta:string}){return <div className="prioridade"><i className={cor}>{icone}</i><div><b>{titulo}</b><p>{texto}</p><span>{etiqueta}</span></div><button>Rever</button></div>}
function Configuracao(){const [etapa,setEtapa]=useState(1);return <section className="configuracao"><div className="config-top"><div><span>CONFIGURAÇÃO BASE</span><h1>Prepare a estrutura da organização</h1><p>Conclua estes três passos para ativar o primeiro fluxo funcional da plataforma.</p></div><b>67% concluído</b></div><div className="progresso"><i/></div><div className="passos">{[["1","Organização","Estrutura, moeda e calendário","Concluído"],["2","Utilizadores","Acessos, funções e âmbito","Em curso"],["3","Colaboradores","Registos e vínculos essenciais","A seguir"]].map((x,i)=><button key={x[1]} className={etapa===i+1?"passo ativo":i===0?"passo concluido":"passo"} onClick={()=>setEtapa(i+1)}><i>{i===0?"✓":x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><em>{x[3]}</em></button>)}</div><div className="config-grid"><article className="cartao estrutura"><Cabecalho sobre={etapa===1?"ORGANIZAÇÃO":etapa===2?"UTILIZADORES":"COLABORADORES"} titulo={etapa===1?"Estrutura organizacional":etapa===2?"Acesso à plataforma":"Registo de colaboradores"} acao="Ver detalhes"/>{etapa===1?<div className="org-tree"><div><i>DH</i><span><b>Demo Holdings</b><small>Grupo · AOA</small></span><em>Ativa</em></div><div><i>SC</i><span><b>Serviços Corporativos</b><small>Unidade · AOA</small></span><em>Ativa</em></div><div><i>OP</i><span><b>Operações</b><small>Unidade · USD</small></span><em>Ativa</em></div></div>:etapa===2?<div className="user-list"><div><i>PF</i><span><b>Pascoal Frederico</b><small>Administrador do tenant</small></span><em>Ativo</em></div><div><i>AM</i><span><b>Ana Manuel</b><small>Gestora Financeira</small></span><em>Convite enviado</em></div><button>＋ Convidar utilizador</button></div>:<div className="empty-state"><i>◎</i><b>148 colaboradores sincronizados</b><p>Os registos estão prontos para validação antes da ativação do Payroll.</p><button className="primario">Rever colaboradores</button></div>}</article><aside className="cartao controlos"><span>ESTADO DOS CONTROLOS</span><h2>Base governada</h2>{[["Isolamento do tenant","Ativo"],["Âmbito organizacional","Configurado"],["Auditoria de alterações","Ativa"],["Segregação de funções","2 alertas"]].map(x=><div key={x[0]}><i>✓</i><span><b>{x[0]}</b><small>{x[1]}</small></span></div>)}<footer><b>Próxima ação recomendada</b><p>Concluir os dois convites pendentes e rever a segregação de funções.</p><button>Resolver agora →</button></footer></aside></div></section>}
