export type PlatformLocale="pt"|"en"|"es"|"fr"|"ru";
export type MessageKey="shell.workspace"|"shell.search"|"shell.overview"|"shell.performance"|"shell.hr"|"shell.activities"|"shell.help"|"shell.home"|"shell.executiveView"|"shell.subscribedModules"|"shell.active"|"module.admin"|"module.finance"|"module.hr"|"module.workforce"|"module.performance"|"module.analytics"|"module.workflow"|"module.integrations";
export const platformLanguages:Record<PlatformLocale,string>={pt:"Português",en:"English",es:"Español",fr:"Français",ru:"Русский"};
const catalogs:Record<PlatformLocale,Record<MessageKey,string>>={
 pt:{"shell.workspace":"ESPAÇO DE TRABALHO","shell.search":"Pesquisar","shell.overview":"Resumo","shell.performance":"Desempenho","shell.hr":"RH","shell.activities":"Atividades","shell.help":"Ajuda","shell.home":"Início","shell.executiveView":"Visão executiva","shell.subscribedModules":"MÓDULOS CONTRATADOS","shell.active":"ativos","module.admin":"Administração","module.finance":"Finance & FP&A","module.hr":"RH","module.workforce":"Workforce Planning","module.performance":"Performance Management","module.analytics":"Analytics & Reporting","module.workflow":"Workflow","module.integrations":"Integration Hub"},
 en:{"shell.workspace":"WORKSPACE","shell.search":"Search","shell.overview":"Overview","shell.performance":"Performance","shell.hr":"HR","shell.activities":"Activities","shell.help":"Help","shell.home":"Home","shell.executiveView":"Executive view","shell.subscribedModules":"SUBSCRIBED MODULES","shell.active":"active","module.admin":"Administration","module.finance":"Finance & FP&A","module.hr":"Human Resources","module.workforce":"Workforce Planning","module.performance":"Performance Management","module.analytics":"Analytics & Reporting","module.workflow":"Workflow","module.integrations":"Integration Hub"},
 es:{"shell.workspace":"ESPACIO DE TRABAJO","shell.search":"Buscar","shell.overview":"Resumen","shell.performance":"Rendimiento","shell.hr":"RR. HH.","shell.activities":"Actividades","shell.help":"Ayuda","shell.home":"Inicio","shell.executiveView":"Vista ejecutiva","shell.subscribedModules":"MÓDULOS CONTRATADOS","shell.active":"activos","module.admin":"Administración","module.finance":"Finanzas y FP&A","module.hr":"Recursos Humanos","module.workforce":"Planificación de plantilla","module.performance":"Gestión del rendimiento","module.analytics":"Analítica e informes","module.workflow":"Flujos de trabajo","module.integrations":"Centro de integraciones"},
 fr:{"shell.workspace":"ESPACE DE TRAVAIL","shell.search":"Rechercher","shell.overview":"Aperçu","shell.performance":"Performance","shell.hr":"RH","shell.activities":"Activités","shell.help":"Aide","shell.home":"Accueil","shell.executiveView":"Vue exécutive","shell.subscribedModules":"MODULES SOUSCRITS","shell.active":"actifs","module.admin":"Administration","module.finance":"Finance et FP&A","module.hr":"Ressources Humaines","module.workforce":"Planification des effectifs","module.performance":"Gestion de la performance","module.analytics":"Analytique et reporting","module.workflow":"Flux de travail","module.integrations":"Centre d’intégration"},
 ru:{"shell.workspace":"РАБОЧЕЕ ПРОСТРАНСТВО","shell.search":"Поиск","shell.overview":"Обзор","shell.performance":"Эффективность","shell.hr":"HR","shell.activities":"Задачи","shell.help":"Помощь","shell.home":"Главная","shell.executiveView":"Обзор руководителя","shell.subscribedModules":"ПОДКЛЮЧЕННЫЕ МОДУЛИ","shell.active":"активно","module.admin":"Администрирование","module.finance":"Финансы и FP&A","module.hr":"Управление персоналом","module.workforce":"Планирование персонала","module.performance":"Управление эффективностью","module.analytics":"Аналитика и отчётность","module.workflow":"Бизнес-процессы","module.integrations":"Центр интеграций"}
};
export function message(locale:PlatformLocale,key:MessageKey){return catalogs[locale][key]}
