"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { formatAOA } from "../../lib/commercial-catalog";
import "../auth.css";
import "./checkout-page.css";

type Payment={id:string;invoice_number:string;provider:string;provider_reference:string;amount_minor:number;currency:string;status:string;tax_status:string;expires_at:string;confirmed_at?:string};
export default function Checkout(){
 const [draft]=useState<{id?:string}|null>(()=>{try{return JSON.parse(localStorage.getItem("ep_checkout_draft")||"null")}catch{return null}});
 const missingDraft=!draft?.id;
 const [payment,setPayment]=useState<Payment|null>(null),[error,setError]=useState(missingDraft?"Não existe um rascunho de checkout. Selecione primeiro um bundle.":""),[busy,setBusy]=useState(!missingDraft),[confirming,setConfirming]=useState(false);
 useEffect(()=>{if(!draft?.id)return;const token=sessionStorage.getItem("ep_access_token")||"";fetch("/api/v1/commerce/payment-intent",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({checkoutId:draft.id})}).then(async r=>({ok:r.ok,status:r.status,body:await r.json()})).then(({ok,status,body})=>{if(!ok){setError(status===401?"A sessão expirou. Entre novamente.":body.error||"Não foi possível preparar o pagamento.");return}setPayment(body.payment)}).finally(()=>setBusy(false))},[draft]);
 async function confirmTest(){if(!payment)return;setConfirming(true);setError("");const token=sessionStorage.getItem("ep_access_token")||"",response=await fetch("/api/v1/commerce/test-confirmation",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({paymentId:payment.id})}),body=await response.json();setConfirming(false);if(!response.ok){setError(body.error||"Não foi possível confirmar o teste.");return}setPayment({...payment,status:"Confirmado",confirmed_at:body.payment.confirmed_at})}
 return <main className="payment-page"><header className="payment-top"><Link href="/" className="auth-brand"><b>EP</b><span>Enterprise Performance</span></Link><span>Checkout seguro · modo de teste</span></header><section className="payment-shell"><div className="payment-heading"><small>PASSO 2 DE 3</small><h1>Pagamento e ativação</h1><p>Este ambiente valida o workflow sem movimentar dinheiro nem emitir uma referência Multicaixa real.</p></div>{busy?<div className="payment-loading">A preparar intenção de pagamento…</div>:error&&!payment?<div className="payment-error"><b>Não foi possível continuar</b><p>{error}</p><Link href="/onboarding/modulos">Voltar à seleção</Link></div>:payment&&<div className="payment-grid"><article className="payment-method"><span className="test-badge">PROXYPAY TEST</span><h2>Referência de simulação</h2><p>Esta referência serve exclusivamente para testar estados, idempotência e auditoria.</p><div className="reference-box"><small>REFERÊNCIA</small><strong>{payment.provider_reference}</strong></div><dl><div><dt>Fatura</dt><dd>{payment.invoice_number}</dd></div><div><dt>Estado</dt><dd className={payment.status==="Confirmado"?"paid":"pending"}>{payment.status}</dd></div><div><dt>Validade</dt><dd>{new Date(payment.expires_at).toLocaleString("pt-AO")}</dd></div></dl><aside><b>Nenhum dado bancário é recolhido</b><p>A integração real será ativada apenas após credenciais, sandbox e assinatura de callbacks ProxyPay.</p></aside></article><aside className="payment-summary"><small>RESUMO</small><h2>Valor validado no servidor</h2><div><span>Subtotal</span><b>{formatAOA(payment.amount_minor)}</b></div><div><span>Imposto</span><b>{payment.tax_status}</b></div><div className="payment-total"><span>Total atual</span><strong>{formatAOA(payment.amount_minor)}</strong></div>{error&&<p className="payment-inline-error">{error}</p>}{payment.status==="Confirmado"?<section className="paid-box"><b>✓ Teste confirmado</b><p>O evento foi processado e auditado. Ainda não foi criada nenhuma empresa.</p></section>:<button onClick={confirmTest} disabled={confirming}>{confirming?"A confirmar…":"Confirmar pagamento de teste"}</button>}<p className="operator-note">A confirmação funciona apenas para a conta Platform Owner aprovada.</p><Link href="/onboarding/modulos">← Alterar seleção</Link></aside></div>}</section></main>
}
