import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const base = { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), createdAt: text("created_at").notNull() };
export const organizations = sqliteTable("organizations", { ...base, code: text("code").notNull(), name: text("name").notNull(), kind: text("kind").notNull(), currency: text("currency").notNull(), status: text("status").notNull() });
export const platformUsers = sqliteTable("platform_users", { ...base, name: text("name").notNull(), email: text("email").notNull(), role: text("role").notNull(), organizationId: text("organization_id"), status: text("status").notNull() });
export const employees = sqliteTable("employees", { ...base, employeeNumber: text("employee_number").notNull(), firstName: text("first_name").notNull(), lastName: text("last_name").notNull(), organizationId: text("organization_id").notNull(), jobTitle: text("job_title").notNull(), hireDate: text("hire_date").notNull(), status: text("status").notNull() });
export const auditEvents = sqliteTable("audit_events", { ...base, action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), actor: text("actor").notNull(), summary: text("summary").notNull() });
export const financialDimensions = sqliteTable("financial_dimensions", { ...base, code: text("code").notNull(), name: text("name").notNull(), description: text("description").notNull(), status: text("status").notNull() });
export const dimensionMembers = sqliteTable("dimension_members", { ...base, dimensionId: text("dimension_id").notNull(), code: text("code").notNull(), name: text("name").notNull(), parentId: text("parent_id"), status: text("status").notNull() });
export const budgetVersions = sqliteTable("budget_versions", { ...base, name: text("name").notNull(), fiscalYear: integer("fiscal_year").notNull(), status: text("status").notNull(), approvedAt: text("approved_at") });
export const performanceEntries = sqliteTable("performance_entries", { ...base, organizationId: text("organization_id").notNull(), period: text("period").notNull(), scenario: text("scenario").notNull(), versionId: text("version_id"), currency: text("currency").notNull(), lineCode: text("line_code").notNull(), lineName: text("line_name").notNull(), dimensionMemberId: text("dimension_member_id"), amountMinor: integer("amount_minor").notNull(), source: text("source").notNull() });
export const salaryProfiles = sqliteTable("salary_profiles", { ...base, employeeId: text("employee_id").notNull(), currency: text("currency").notNull(), periodicity: text("periodicity").notNull(), baseMinor: integer("base_minor").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to"), dimensionMemberId: text("dimension_member_id"), status: text("status").notNull() });
export const payrollComponents = sqliteTable("payroll_components", { ...base, code: text("code").notNull(), name: text("name").notNull(), category: text("category").notNull(), method: text("method").notNull(), valueMinor: integer("value_minor"), rateBps: integer("rate_bps"), calculationOrder: integer("calculation_order").notNull(), status: text("status").notNull() });
export const payrollAssignments = sqliteTable("payroll_assignments", { ...base, employeeId: text("employee_id").notNull(), componentId: text("component_id").notNull() });
export const payrollRuns = sqliteTable("payroll_runs", { ...base, period: text("period").notNull(), currency: text("currency").notNull(), status: text("status").notNull(), employeeCount: integer("employee_count").notNull(), grossMinor: integer("gross_minor").notNull(), deductionMinor: integer("deduction_minor").notNull(), employerMinor: integer("employer_minor").notNull(), netMinor: integer("net_minor").notNull(), closedAt: text("closed_at") });
export const payrollRunLines = sqliteTable("payroll_run_lines", { ...base, runId: text("run_id").notNull(), employeeId: text("employee_id").notNull(), baseMinor: integer("base_minor").notNull(), grossMinor: integer("gross_minor").notNull(), deductionMinor: integer("deduction_minor").notNull(), employerMinor: integer("employer_minor").notNull(), netMinor: integer("net_minor").notNull(), calculationHash: text("calculation_hash").notNull(), inputSnapshot: text("input_snapshot").notNull() });
export const workforceCostPostings = sqliteTable("workforce_cost_postings", { ...base, runId: text("run_id").notNull(), runLineId: text("run_line_id").notNull(), employeeId: text("employee_id").notNull(), organizationId: text("organization_id").notNull(), dimensionMemberId: text("dimension_member_id"), period: text("period").notNull(), currency: text("currency").notNull(), grossMinor: integer("gross_minor").notNull(), employerMinor: integer("employer_minor").notNull(), totalMinor: integer("total_minor").notNull(), sourceHash: text("source_hash").notNull(), postedAt: text("posted_at").notNull() });
export const managementReports = sqliteTable("management_reports", { ...base, reportNumber: integer("report_number").notNull(), title: text("title").notNull(), template: text("template").notNull(), period: text("period").notNull(), currency: text("currency").notNull(), budgetVersionId: text("budget_version_id"), status: text("status").notNull(), payloadJson: text("payload_json").notNull(), inputHash: text("input_hash").notNull(), createdBy: text("created_by").notNull() });
