import {classifyDataError} from "../lib/api-error";

type CompetencySecurity={tenantId:string;organizationId:string|null;email:string;role:string};
const uid=()=>crypto.randomUUID();
const respondError=(error:unknown)=>{const x=classifyDataError(error,"Não foi possível processar competências e feedback.");return Response.json({error:x.message,code:x.code},{status:x.status})};

export async function competenciesApi(request:Request,db:D1Database,security:CompetencySecurity){
 try{
  const tenant=security.tenantId,scope=security.organizationId,now=new Date().toISOString(),governor=["Administrador","Recursos Humanos"].includes(security.role),tenantGovernor=governor&&!scope;
  const snapshot=async()=>{const [frameworks,competencies,rounds,participants,reviews,people,results,audit]=await Promise.all([
   db.prepare("SELECT f.*,(SELECT COUNT(*) FROM competency_definitions c WHERE c.tenant_id=f.tenant_id AND c.framework_id=f.id AND c.status='Ativa') competency_count,(SELECT COALESCE(SUM(weight_bps),0) FROM competency_definitions c WHERE c.tenant_id=f.tenant_id AND c.framework_id=f.id AND c.status='Ativa') total_weight_bps FROM competency_frameworks f WHERE f.tenant_id=? ORDER BY f.created_at DESC").bind(tenant).all(),
   db.prepare("SELECT * FROM competency_definitions WHERE tenant_id=? ORDER BY framework_id,category,code").bind(tenant).all(),
   db.prepare("SELECT r.*,f.name framework_name,v.subject_email,s.name subject_name,v.organization_id,o.name organization_name,(SELECT COUNT(*) FROM feedback_360_participants p WHERE p.tenant_id=r.tenant_id AND p.round_id=r.id) participant_count,(SELECT COUNT(*) FROM feedback_360_participants p WHERE p.tenant_id=r.tenant_id AND p.round_id=r.id AND p.status='Submetido') submitted_count FROM feedback_360_rounds r JOIN competency_frameworks f ON f.id=r.framework_id AND f.tenant_id=r.tenant_id JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id JOIN platform_users s ON lower(s.email)=lower(v.subject_email) AND s.tenant_id=v.tenant_id JOIN organizations o ON o.id=v.organization_id AND o.tenant_id=v.tenant_id WHERE r.tenant_id=? AND (? IS NULL OR v.organization_id=?) ORDER BY r.created_at DESC").bind(tenant,scope,scope).all(),
   db.prepare("SELECT p.*,r.confidentiality,r.status round_status FROM feedback_360_participants p JOIN feedback_360_rounds r ON r.id=p.round_id AND r.tenant_id=p.tenant_id JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id WHERE p.tenant_id=? AND (? IS NULL OR v.organization_id=?) ORDER BY p.invited_at").bind(tenant,scope,scope).all<Record<string,unknown>>(),
   db.prepare("SELECT r.id,r.subject_email,s.name subject_name,r.organization_id,c.name cycle_name FROM performance_reviews r JOIN platform_users s ON lower(s.email)=lower(r.subject_email) AND s.tenant_id=r.tenant_id JOIN performance_cycles c ON c.id=r.cycle_id AND c.tenant_id=r.tenant_id WHERE r.tenant_id=? AND r.status<>'Cancelada' AND (? IS NULL OR r.organization_id=?) ORDER BY r.created_at DESC").bind(tenant,scope,scope).all(),
   db.prepare("SELECT name,email,role,organization_id FROM platform_users WHERE tenant_id=? AND status='Ativo' AND (? IS NULL OR organization_id IS NULL OR organization_id=?) ORDER BY name").bind(tenant,scope,scope).all(),
   db.prepare("SELECT x.round_id,x.competency_id,c.code,c.name,c.category,c.weight_bps,ROUND(SUM(x.rating_bps*p.weight_bps)*1.0/SUM(p.weight_bps)) score_bps,COUNT(*) response_count FROM feedback_360_responses x JOIN feedback_360_participants p ON p.id=x.participant_id AND p.tenant_id=x.tenant_id JOIN competency_definitions c ON c.id=x.competency_id AND c.tenant_id=x.tenant_id JOIN feedback_360_rounds r ON r.id=x.round_id AND r.tenant_id=x.tenant_id JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id WHERE x.tenant_id=? AND r.status='Fechado' AND (? IS NULL OR v.organization_id=?) GROUP BY x.round_id,x.competency_id,c.code,c.name,c.category,c.weight_bps ORDER BY x.round_id,c.category,c.code").bind(tenant,scope,scope).all(),
   scope?Promise.resolve({results:[]}):db.prepare("SELECT * FROM audit_events WHERE tenant_id=? AND entity_type IN ('competencyFramework','feedback360') ORDER BY created_at DESC LIMIT 15").bind(tenant).all()
  ]);const safeParticipants=participants.results.filter(p=>governor||String(p.evaluator_email).toLowerCase()===security.email.toLowerCase()).map(p=>({...p,evaluator_email:p.confidentiality==="Confidencial"&&!governor&&String(p.evaluator_email).toLowerCase()!==security.email.toLowerCase()?null:p.evaluator_email}));return{frameworks:frameworks.results,competencies:competencies.results,rounds:rounds.results,participants:safeParticipants,reviews:reviews.results,people:people.results,results:results.results,audit:audit.results}};
  if(request.method==="GET")return Response.json(await snapshot());if(request.method!=="POST")return Response.json({error:"Método não permitido."},{status:405});
  const body=await request.json() as Record<string,string>;let entityId=body.frameworkId||body.roundId||"",entityType="feedback360";
  if(body.type==="createFramework"){
   if(!tenantGovernor)return Response.json({error:"A configuração global exige Administrador ou Recursos Humanos com âmbito de tenant."},{status:403});if(!body.name?.trim())return Response.json({error:"O nome do framework é obrigatório."},{status:400});entityId=uid();entityType="competencyFramework";await db.prepare("INSERT INTO competency_frameworks (id,tenant_id,name,description,status,created_by,created_at) VALUES (?,?,?,?,'Rascunho',?,?)").bind(entityId,tenant,body.name.trim(),body.description?.trim()||null,security.email,now).run();
  }else if(body.type==="addCompetency"){
   if(!tenantGovernor)return Response.json({error:"A configuração global exige Administrador ou Recursos Humanos com âmbito de tenant."},{status:403});const weight=Math.round(Number((body.weight||"").replace(",","."))*100);if(!body.frameworkId||!body.code?.trim()||!body.name?.trim()||!body.category?.trim()||!Number.isInteger(weight)||weight<1||weight>10000)return Response.json({error:"Framework, código, nome, categoria e peso válido são obrigatórios."},{status:400});entityType="competencyFramework";await db.prepare("INSERT INTO competency_definitions (id,tenant_id,framework_id,code,name,description,category,weight_bps,status,created_at) VALUES (?,?,?,?,?,?,?,?, 'Ativa',?)").bind(uid(),tenant,body.frameworkId,body.code.trim().toUpperCase(),body.name.trim(),body.description?.trim()||null,body.category.trim(),weight,now).run();
  }else if(body.type==="activateFramework"){
   if(!tenantGovernor)return Response.json({error:"A ativação global exige Administrador ou Recursos Humanos com âmbito de tenant."},{status:403});const f=await db.prepare("SELECT * FROM competency_frameworks WHERE id=? AND tenant_id=? AND status='Rascunho'").bind(body.frameworkId,tenant).first<Record<string,unknown>>();if(!f)return Response.json({error:"Framework em rascunho não encontrado."},{status:404});if(String(f.created_by).toLowerCase()===security.email.toLowerCase())return Response.json({error:"Maker-checker: o criador não pode ativar o próprio framework."},{status:403});const result=await db.prepare("UPDATE competency_frameworks SET status='Ativo',activated_by=?,activated_at=? WHERE id=? AND tenant_id=? AND status='Rascunho'").bind(security.email,now,body.frameworkId,tenant).run();if(!Number(result.meta.changes||0))return Response.json({error:"O framework foi atualizado em paralelo."},{status:409});entityType="competencyFramework";
  }else if(body.type==="createRound"){
   if(!governor)return Response.json({error:"A criação da ronda exige Administrador ou Recursos Humanos."},{status:403});if(!body.reviewId||!body.frameworkId||!/^\d{4}-\d{2}-\d{2}$/.test(body.dueDate||"")||!["Identificado","Confidencial"].includes(body.confidentiality))return Response.json({error:"Avaliação, framework, prazo e confidencialidade são obrigatórios."},{status:400});const review=await db.prepare("SELECT id FROM performance_reviews WHERE id=? AND tenant_id=? AND status<>'Cancelada' AND (? IS NULL OR organization_id=?)").bind(body.reviewId,tenant,scope,scope).first();if(!review)return Response.json({error:"Avaliação fora do âmbito autorizado."},{status:403});entityId=uid();await db.prepare("INSERT INTO feedback_360_rounds (id,tenant_id,review_id,framework_id,due_date,confidentiality,status,created_by,created_at) VALUES (?,?,?,?,?,?,'Rascunho',?,?)").bind(entityId,tenant,body.reviewId,body.frameworkId,body.dueDate,body.confidentiality,security.email,now).run();
  }else if(body.type==="addParticipant"){
   if(!governor)return Response.json({error:"A configuração da ronda exige Administrador ou Recursos Humanos."},{status:403});const round=await db.prepare("SELECT r.id FROM feedback_360_rounds r JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id WHERE r.id=? AND r.tenant_id=? AND r.status='Rascunho' AND (? IS NULL OR v.organization_id=?)").bind(body.roundId,tenant,scope,scope).first();if(!round)return Response.json({error:"Ronda fora do âmbito autorizado."},{status:403});const weight=Math.round(Number((body.weight||"").replace(",","."))*100);if(!body.roundId||!body.evaluatorEmail||!["Autoavaliação","Gestor","Par","Reporte direto","Outro"].includes(body.relationship)||!Number.isInteger(weight)||weight<1||weight>10000)return Response.json({error:"Ronda, participante, relação e peso válido são obrigatórios."},{status:400});await db.prepare("INSERT INTO feedback_360_participants (id,tenant_id,round_id,evaluator_email,relationship,weight_bps,status,invited_at) VALUES (?,?,?,?,?,?,'Pendente',?)").bind(uid(),tenant,body.roundId,body.evaluatorEmail.toLowerCase(),body.relationship,weight,now).run();
  }else if(body.type==="openRound"){
   if(!governor)return Response.json({error:"A abertura exige Administrador ou Recursos Humanos."},{status:403});const round=await db.prepare("SELECT r.* FROM feedback_360_rounds r JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id WHERE r.id=? AND r.tenant_id=? AND r.status='Rascunho' AND (? IS NULL OR v.organization_id=?)").bind(body.roundId,tenant,scope,scope).first<Record<string,unknown>>();if(!round)return Response.json({error:"Ronda em rascunho não encontrada no âmbito autorizado."},{status:404});if(String(round.created_by).toLowerCase()===security.email.toLowerCase())return Response.json({error:"Maker-checker: o criador não pode abrir a própria ronda."},{status:403});const result=await db.prepare("UPDATE feedback_360_rounds SET status='Aberto',opened_by=?,opened_at=? WHERE id=? AND tenant_id=? AND status='Rascunho'").bind(security.email,now,body.roundId,tenant).run();if(!Number(result.meta.changes||0))return Response.json({error:"A ronda foi atualizada em paralelo."},{status:409});
  }else if(body.type==="submitFeedback"){
   const participant=await db.prepare("SELECT p.*,r.framework_id FROM feedback_360_participants p JOIN feedback_360_rounds r ON r.id=p.round_id AND r.tenant_id=p.tenant_id JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id WHERE p.id=? AND p.tenant_id=? AND p.status='Pendente' AND r.status='Aberto' AND lower(p.evaluator_email)=lower(?) AND (? IS NULL OR v.organization_id=?)").bind(body.participantId,tenant,security.email,scope,scope).first<Record<string,unknown>>();if(!participant)return Response.json({error:"Pedido de feedback pendente não encontrado para este utilizador."},{status:404});const input=JSON.parse(body.responses||"[]") as Array<{competencyId:string;rating:number;comment?:string}>,definitions=await db.prepare("SELECT id FROM competency_definitions WHERE tenant_id=? AND framework_id=? AND status='Ativa' ORDER BY id").bind(tenant,participant.framework_id).all<Record<string,unknown>>(),expected=new Set(definitions.results.map(x=>String(x.id)));if(input.length!==expected.size||new Set(input.map(x=>x.competencyId)).size!==expected.size||input.some(x=>!expected.has(x.competencyId)||!Number.isInteger(Number(x.rating))||Number(x.rating)<1||Number(x.rating)>5))return Response.json({error:"Responda uma vez a todas as competências na escala de 1 a 5."},{status:400});const commands=input.map(x=>db.prepare("INSERT INTO feedback_360_responses VALUES (?,?,?,?,?,?,?,?)").bind(uid(),tenant,participant.round_id,participant.id,x.competencyId,Number(x.rating)*2000,x.comment?.trim()||null,now));commands.push(db.prepare("UPDATE feedback_360_participants SET status='Submetido',submitted_at=? WHERE id=? AND tenant_id=? AND status='Pendente'").bind(now,participant.id,tenant));const results=await db.batch(commands);if(!Number(results.at(-1)?.meta.changes||0))return Response.json({error:"O feedback foi submetido em paralelo."},{status:409});entityId=String(participant.round_id);
  }else if(body.type==="closeRound"){
   if(!governor)return Response.json({error:"O fecho exige Administrador ou Recursos Humanos."},{status:403});const rows=await db.prepare("SELECT c.id,c.weight_bps,SUM(x.rating_bps*p.weight_bps)*1.0/SUM(p.weight_bps) score FROM feedback_360_rounds r JOIN performance_reviews v ON v.id=r.review_id AND v.tenant_id=r.tenant_id JOIN competency_definitions c ON c.framework_id=r.framework_id AND c.tenant_id=r.tenant_id JOIN feedback_360_responses x ON x.round_id=r.id AND x.competency_id=c.id AND x.tenant_id=r.tenant_id JOIN feedback_360_participants p ON p.id=x.participant_id AND p.tenant_id=x.tenant_id WHERE r.id=? AND r.tenant_id=? AND r.status='Aberto' AND (? IS NULL OR v.organization_id=?) GROUP BY c.id,c.weight_bps").bind(body.roundId,tenant,scope,scope).all<Record<string,unknown>>();if(!rows.results.length)return Response.json({error:"A ronda ainda não possui respostas consolidadas no âmbito autorizado."},{status:409});const total=rows.results.reduce((n,x)=>n+Number(x.weight_bps),0),overall=Math.round(rows.results.reduce((n,x)=>n+Number(x.score)*Number(x.weight_bps),0)/total);const result=await db.prepare("UPDATE feedback_360_rounds SET status='Fechado',overall_score_bps=?,closed_by=?,closed_at=? WHERE id=? AND tenant_id=? AND status='Aberto'").bind(overall,security.email,now,body.roundId,tenant).run();if(!Number(result.meta.changes||0))return Response.json({error:"Todos os participantes devem submeter antes do fecho."},{status:409});
  }else return Response.json({error:"Operação de competências não suportada."},{status:400});
  await db.prepare("INSERT INTO audit_events (id,tenant_id,action,entity_type,entity_id,actor,summary,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(uid(),tenant,body.type,entityType,entityId,security.email,`Competências 360: ${body.type}`,now).run();return Response.json(await snapshot(),{status:201});
 }catch(error){return respondError(error)}
}
